### ISSUE TITLE
Accuracy of non-power 2 data

### ISSUE THREAD

**Issue by mikaem** [pyFFTW/pyFFTW#105]
Hi

I'm getting some unwanted errors for data of size different than power of 2. Minimal example is

    from pyfftw.interfaces.numpy_fft import irfftn, irfft, ifft
    import numpy as np

    N = 12
    b = np.random.random((N, N, N/2+1)) + 1j*np.random.random((N, N, N/2+1))

    ####### pyfftw
    c = irfftn(b, axes=(0,1,2))
    c2 = irfft(ifft(ifft(b, axis=0), axis=1), axis=2)
    print np.linalg.norm(c-c2)

    ####### numpy
    c3 = np.fft.irfftn(b, axes=(0,1,2))
    c4 = np.fft.irfft(np.fft.ifft(np.fft.ifft(b, axis=0), axis=1), axis=2)
    print np.linalg.norm(c3-c4)

prints:
6.23715470854e-08
0.0

So numpy produces the same result using either irfftn(.) or irfft(ifft(ifft(.))), whereas pyfftw produces two results with a rather large error norm on two operations that should be identical. If I use instead N = 16 (a power of 2) then error is printed as 0.0, 0.0 for both numpy and pyfftw. 
Are these results reproducable by others or could it be my installation? Are there any settings that could take care of this?  I would expect errors near 1e-15 and not 1e-7 for FFTs in double precision, so to me the errornorm looks odd...

**Comment by hgomersall** [comment]
I can't reproduce this on my machine. I get errors ~1e-16. What version of pyFFTW are you running? Is your version pre this fix: https://github.com/pyFFTW/pyFFTW/commit/157032843d680506a568b309508eff97d7a6142e ?

**Comment by mikaem** [comment]
Hi

I'm on 0.9.2, which is prior to your suggested fix, so I guess I just need to upgrade:-)

Thanks

Mikael
