### ISSUE TITLE
Use cuFFT when CUDA is available

### ISSUE THREAD

**Issue by carlthome** [pyFFTW/pyFFTW#107]
It would be very neat to use the GPU transparently, if available on the system. Perhaps pyFFTW could wrap cuFFT as well at FFTW?

**Comment by hgomersall** [comment]
Ha. I'd love this to happen - perhaps with an package level flag - `pyfftw.use_gpu = True`. How does the API compare?

**Comment by carlthome** [comment]
Cool! Unfortunately the API's are pretty different, probably due to how a GPU wants things to work (it uses "plans" for setting input and output dimensions), but I think it would be well worth the effort, as it easily would make pyFFTW the go-to-package for FFT in Python.

```C
#define NX 64
#define NY 64
#define NZ 128

cufftHandle plan;
cufftComplex *data1, *data2;
cudaMalloc((void**)&data1, sizeof(cufftComplex)*NX*NY*NZ);
cudaMalloc((void**)&data2, sizeof(cufftComplex)*NX*NY*NZ);

/* Create a 3D FFT plan. */
cufftPlan3d(&plan, NX, NY, NZ, CUFFT_C2C);

/* Transform the first signal in place. */
cufftExecC2C(plan, data1, data1, CUFFT_FORWARD);

/* Transform the second signal using the same plan. */
cufftExecC2C(plan, data2, data2, CUFFT_FORWARD);

/* Destroy the cuFFT plan. */
cufftDestroy(plan);
cudaFree(data1); cudaFree(data2);
```

**Comment by hgomersall** [comment]
I think this is best done by an external package. It seems a bit mucky to build this into pyFFTW, which has a pretty clear remit. I'm happy to think about how pyFFTW things can be tweaked or augmented to make this easier though.

**Comment by grlee77** [comment]
@carlthome 
Are you familiar with [scikit-cuda](https://github.com/lebedov/scikit-cuda)?  It has python interfaces to cuFFT.  It depends on [pyCUDA](https://github.com/inducer/pycuda) which offers numpy-like GPU arrays.

**Comment by carlthome** [comment]
After thinking about this, I totally agree @hgomersall. It's a bit too mucky and pyFFTW is pretty great as is.
