### ISSUE TITLE
pyfftw does not appear to be using available wisdom files

### ISSUE THREAD

**Issue by TrekkieByDay** [pyFFTW/pyFFTW#110]
During timing tests, I'm finding that there does not seem to be a difference between running with an existing wisdom file and without. The array size is 6550x6550, complex64. The wisdom file is imported successfully, but the call to pyfftw.builders.fft2 and pyfftw.builders.ifft2 take the same amount of time. Do you have any suggestions?

**Comment by hgomersall** [comment]
Some example code would be useful...

**Comment by TrekkieByDay** [comment]
So we did solve it... we didn't realize that import_wisdom returns a tuple of bools describing whether it was successful... we assumed (incorrectly) that it would raise a warning or exception if it failed. :( When we realized that, we realized that it was not importing correctly. We went to pickling the wisdom object directly and that worked.

**Comment by hgomersall** [comment]
np

**Comment by hgomersall** [comment]
Actually, it would still be helpful to have an example. It probably _should_ raise an exception if that makes sense.

**Comment by TrekkieByDay** [comment]
So this is how we now deal with the import_wisdom call:

    import_results = pyfftw.import_wisdom(wisdom)
    if not all(import_results):
        msg = 'Import wisdom failed! Wisdom will be recaulculated!'
        warnings.warn(msg)

We had previously not bothered with the output of `import_wisdom`. I don't know that you need to except out or raise a warning.. it makes sense in our case, but it totally makes sense not to as well especially if compute time is not as big an issue for you.

**Comment by s-sajid-ali** [comment]
I'm having the same issue. [Here](https://pastebin.com/phX74Ac1) is the test code. 

What the code does :  Perform a 2D FFT. Pickle and save wisdom. Forget wisdom. Import and perform the FFT again with using wisdom.

This is the output : 
```
(intelpy3) [sajid@xrmlite tests]$ python test_wisdom_import.py
10000 4 3.1428067684173584
Traceback (most recent call last):
  File "test_wisdom_import.py", line 64, in <module>
    FFT2(a,flag='WISDOM_ONLY',threads=t)
  File "test_wisdom_import.py", line 18, in FFT2
    threads=threads, planning_timelimit=None)
  File "pyfftw/pyfftw.pyx", line 1110, in pyfftw.pyfftw.FFTW.__cinit__ (/tmp/sajid/spack-stage/spack-stage-059qa7rl/pyFFTW-0.10.4/pyfftw/pyfftw.c:10829)
RuntimeError: No FFTW wisdom is known for this plan.
```
