### ISSUE TITLE
pyfftw fails with ImportError/undefined symbol fftwl_plan_with_nthreads

### ISSUE THREAD

**Issue by ghisvail** [pyFFTW/pyFFTW#112]
Forwarded from [Debian-Bug#826036](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826036). Also reported on [ubuntuforums](http://ubuntuforums.org/showthread.php?t=2326008).

**Comment by hgomersall** [comment]
@ghisvail are you able to reproduce this? Is it an issue with `libfftw3l_threads.so` (the file missing or the symbol missing), or is it a problem with linking against the correct `.so` file?

**Comment by ghisvail** [comment]
Yes, and on a clean chroot. The test suite fails with the very same error.

**Comment by hgomersall** [comment]
Are you able to answer the questions I posted on [ubuntuforums](http://ubuntuforums.org/showthread.php?t=2326008)?

**Comment by ghisvail** [comment]
I get:
```
>>> nm -D /usr/lib/*/libfftw3l_threads.so | grep fftwl_plan_with_nthreads

0000000000001f90 T fftwl_plan_with_nthreads
```

so the symbol seems present.

**Comment by ghisvail** [comment]
Dammit I know what happened. I had to modify `setup.py` to use pkg-config to allow for dynamic detection of fftw with all the precision variants. However:
```
>>> pkg-config --libs fftw3

-lfftw3
```
The pkg-config file does not return the additional `-lfftw3_threads` :-1:. So it is a bug in the pkg-config file of fftw3, but it also my fault for blindly presuming this would work in the first place. I can fix this, and will ask Ubuntu to SRU the fix on 16.04.

**Comment by hgomersall** [comment]
Good news :) well done and thanks.

**Comment by hgomersall** [comment]
Can we now close this issue?

**Comment by hgomersall** [comment]
Actually, I'm surprised is doesn't complain at link time.

**Comment by ghisvail** [comment]
Indeed. Closed.

**Comment by ghisvail** [comment]
> Actually, I'm surprised is doesn't complain at link time.

Me too.
