### ISSUE TITLE
test/_*.py missing from release tarball on PyPI

### ISSUE THREAD

**Issue by ghisvail** [pyFFTW/pyFFTW#114]
The current tarball hosted on PyPI is missing the private `test/_*.py` files, which are necessary for the numpy and scipy interface tests to run. Please consider updating your manifest to include the missing files and upload a new version.

**Comment by hgomersall** [comment]
Fixed in git. I'll make a release at some point soon. Do you need it for the Debian stuff?

**Comment by ghisvail** [comment]
> Do you need it for the Debian stuff?

Yes, that's the main reason why the tests have been disabled in the packaging. I would have caught #112 much earlier otherwise, which I am now in the process of repairing.

> I'll make a release at some point soon.

The sooner the better on my side.

**Comment by hgomersall** [comment]
Ok, I'll try to get on it tomorrow.

**Comment by ghisvail** [comment]
That would be great. Meanwhile, I'll forward the fix for #112 to Ubuntu so they can clear my mess asap.

**Comment by hgomersall** [comment]
Great - I wouldn't worry too much; using pypi should work fine and isn't hard to do nowadays. I agree it's not ideal though.

**Comment by ghisvail** [comment]
any news ?

**Comment by hgomersall** [comment]
I've just done the release. It's a slight mess (I forgot to merge release changes before tagging, so the CHANGELOG is not perfect). Should do the job though.

**Comment by ghisvail** [comment]
Addressed in latest release. Closing. Thanks.
