### ISSUE TITLE
problem with 0.10.2 packages on pypi

### ISSUE THREAD

**Issue by grlee77** [pyFFTW/pyFFTW#118]
The static linking changes do no seem to have made it into the source .tar.gz for the 0.10.2 release on pipy (downloaded from:  https://files.pythonhosted.org/packages/a0/27/8e563cf640af13e25c84960e9425be62638cc6f1cb14d03b025602a591b3/pyFFTW-0.10.2.tar.gz)

However, the source in the github releases page do have the desired changes.  This may require another version bump to fix on pypi as I don't think you can re-upload files with the same names.

**Comment by hgomersall** [comment]
Ach, I've spent a fair chunk of today trying to get travis to auto upload, but I can't get the encryption keys working. Anyway, I've pushed a new release that should work.

**Comment by grlee77** [comment]
The 0.10.3 release is working without problems.  Thanks
