### ISSUE TITLE
Incorrectly tagged release (v10.2 instead of v0.10.2)

### ISSUE THREAD

**Issue by lpsinger** [pyFFTW/pyFFTW#124]
I maintain a MacPorts port of your project. I noticed that the most recent release was tagged v10.2 instead of v0.10.2. If this is a mistake, would you please create a new tag?

**Comment by hgomersall** [comment]
Ach, it's all going wrong! I spent about 8 hours yesterday trying to fix various issues with the way in which the CI tools handle the tags, and in the process made no end of brokenness.

The tags are now fixed, but if you want to help in anyway with getting travis to not be such a PITA I'd really appreciate it! Also, I understand travis can now do the mac stuff automatically, so perhaps that would be an incentive :)

**Comment by hgomersall** [comment]
There should be no issue tracking the latest releases from PyPI, but they're not changing much, it's just me trying to make things automated and having to cope with cloud based black boxes.

**Comment by hgomersall** [comment]
I'm inclined to say just ignore 0.10.2. It and 0.10.3 were broken. Use the new release (which hopefully I've fixed!).

**Comment by lpsinger** [comment]
Thanks! Fixed in [MacPorts r149239](https://trac.macports.org/changeset/149239).
