### ISSUE TITLE
Runtime failure on architectures without long-double FFTW

### ISSUE THREAD

**Issue by ghisvail** [pyFFTW/pyFFTW#127]
I have updated the [Debian packaging](https://buildd.debian.org/status/package.php?p=pyfftw) with release `0.10.4` and the build now fails for some architectures, some of these considered major. On `armel`, `armhf` and `mips[el]`, it seems that importing the module triggers an import of the long-double FFTW although the latter is not available and not being built against.

**Comment by hgomersall** [comment]
Ok - did this work previously? Is it possible to see what change causes it by comparison to earlier releases?

**Comment by ghisvail** [comment]
The testsuite was disabled previously because of #114. Now that the testsuite is enabled as part of the package build, the errors are coming.

**Comment by ghisvail** [comment]
This is the patch I am currently applying to get the build to work for architectures without long-double FFTW:
```
From: Ghislain Antony Vaillant <ghisvail@gmail.com>
Date: Mon, 1 Feb 2016 23:08:52 +0000
Subject: Detect fftw libraries using pkgconfig.

---
 setup.py | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)

--- a/setup.py
+++ b/setup.py
@@ -120,8 +120,10 @@
         libraries = ['libfftw3-3', 'libfftw3f-3', 'libfftw3l-3']
 
     else:
-        libraries = ['fftw3', 'fftw3f', 'fftw3l', 'fftw3_threads',
-                     'fftw3f_threads', 'fftw3l_threads']
+        import pkgconfig
+        libraries = ['fftw3', 'fftw3_threads', 'fftw3f', 'fftw3f_threads']
+        if pkgconfig.exists('fftw3l'):
+            libraries.extend(['fftw3l', 'fftw3l_threads'])
 
     return libraries

```
But the [outcome](https://buildd.debian.org/status/fetch.php?pkg=pyfftw&arch=armel&ver=0.10.4%2Bdfsg1-1&stamp=1465321508) of running the testsuite for architectures without long-double suggests that this is probably not enough.

**Comment by hgomersall** [comment]
Yes, this is what I suspected. I think this issue of not requiring all the library versions needs to be sorted properly, and is in my long term todo list. Do you agree this bug is essentially the same as #70?

**Comment by ghisvail** [comment]
> Do you agree this bug is essentially the same as #70?

Agreed.

Solving #70, #127 should be split between build-time and runtime considerations. For build-time, `pkgconfig` does the job quite nicely. For runtime, I guess you'd have to implement some sort of detection via a build-time flag or some sort of exception (via `ctypes` perhaps)?
