### ISSUE TITLE
Switch cache to LRU?

### ISSUE THREAD

**Issue by anntzer** [pyFFTW/pyFFTW#129]
Python 3 provides an implementation of an least-recently-used cache (https://docs.python.org/3/library/functools.html#functools.lru_cache) (which is written in C since 3.5, so it'll be hard to beat its performance).  Using it for caching would avoid having to deal with multithreading, and the availability of `cache_info()` would let the user have a better idea of how to tune the cache parameter (in this case, the cache size, rather than the cache lifetime; I feel that the latter is difficult to set in an informed manner).

**Comment by hgomersall** [comment]
Hmmm, that's not a bad idea. Has it been back ported? Fancy a bash at a PR?

I suggest we could run the two in parallel for a while.

**Comment by anntzer** [comment]
Here's the backport: https://pypi.python.org/pypi/functools32
I don't mind writing a PR that would switch to only using `lru_cache`, but maintaining both caches within the same codebase seems to tricky to be worth it?

**Comment by hgomersall** [comment]
The problem is, we'd add a new dependency and break legacy code. Is this desirable for a marginal enhancement. What is the problem with the current cache? Why is the multithreading so bad?

The other problem is that we don't really tune the cache *size* so much as the number of cached items. It would be certainly be the case that having several big objects could overwhelm RAM and which would not be cleared easily.

**Comment by anntzer** [comment]
It's not that multithreading is bad (although there were certainly a few (now fixed) bugs related to it), but rather that it is very difficult to know whether the timeout you set is reasonable.  In a sense, just providing the same statistics (number of cache hits, number of cache misses) would already by an improvement...

If you don't want to add an external dependency, note that the implementation of `lru_cache` is less than 100 lines long (if you don't need to support py2.6) so we may as well copypaste it.

**Comment by hgomersall** [comment]
I'd suggest that it's quite easy to know if the timeout is reasonable - if the time between calls to the interface layer is short compared to the timeout, then it's too long. The predominant use case of the cache is for calling through the `*py_interface` layers, in which rapid repeated calls to objects can be optimised through caching. If the calls are a relatively rare, there is little to be gained (except for perhaps the unusual case in which there are many objects that are called rapidly with repeats relatively rarely).

Of course, FFTW still has it's wisdom, so the actual time of creation for an FFTW object is quite short, so for rare callings this should be the way object creation is optimised.

If this isn't clear, perhaps it needs updating in the docs.

**Comment by anntzer** [comment]
Again, it's sometimes hard to tell how often, (in absolute time) a call to pyfftw occurs in absolute numbers (without instrumenting the code), whereas it is typically easier to figure out a reasonable cache size.
The other reason for the suggestion is that (if you're willing to declare an additional dependency) this would make the codebase a bit simpler.
On the other hand I don't feel strongly about this so feel free to close this if you don't like the suggestion.

**Comment by hgomersall** [comment]
It actually doesn't matter about the absolute time - only that the cache time is quite a bit longer than the creation time - this is easy to know (basically, a cache of a second or so is almost certainly enough except for some unusual cases). If you need to seriously optimise, then moving away from the interfaces is the correct approach, which totally removes the cache concerns.

I agree with the simplification issue but I think I'm going to stick with what we have to avoid breakage - I don't think you've convinced me yet of the value of such a change (but thank you!).
