### ISSUE TITLE
Citation preferences?

### ISSUE THREAD

**Issue by bmorris3** [pyFFTW/pyFFTW#132]
How should pyFFTW by cited in academic journals?

**Comment by hgomersall** [comment]
Is there some kind of standard for referencing software packages? I sort of make it up as I go along. I certainly think if you're citing pyFFTW, FFTW should be cited as well. Regarding pyFFTW, however you fancy - a link to the github page is probably easiest. We're not going anywhere soon :)

**Comment by bmorris3** [comment]
There's no standard for sure, but one option is to mint a DOI for one version of pyFFTW. You can learn more about doing that with [this tutorial](https://guides.github.com/activities/citable-code/) if you're interested. I'm happy to use a link otherwise.

**Comment by hgomersall** [comment]
I've done a temporary DOI here:

[![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.59508.svg)](http://dx.doi.org/10.5281/zenodo.59508)

I've set up webhooks to the github repository so I'll update it when I do a release.

**Comment by bmorris3** [comment]
Thanks!
