### ISSUE TITLE
Error while installing: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by spraharsh** [pyFFTW/pyFFTW#133]
I tried installing pyfftw after checking whether all the dependencies are installed.

I end up getting
`Searching for pyfftw
Reading https://pypi.python.org/simple/pyfftw/
Best match: pyFFTW 0.10.4
Downloading https://pypi.python.org/packages/c2/2e/b25edc6960fc837e915eb1b38e5f0e3013e32e90aff14a1d0f4556b3d145/pyFFTW-0.10.4.tar.gz#md5=7fb59450308881bb48d9f178947d950e
Processing pyFFTW-0.10.4.tar.gz
Writing /tmp/easy_install-nawY2E/pyFFTW-0.10.4/setup.cfg
Running pyFFTW-0.10.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-nawY2E/pyFFTW-0.10.4/egg-dist-tmp-zA1RzQ
In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /tmp/easy_install-nawY2E/pyFFTW-0.10.4/pyfftw/pyfftw.c:268:
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:27:0,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /tmp/easy_install-nawY2E/pyFFTW-0.10.4/pyfftw/pyfftw.c:268:
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/__multiarray_api.h:1448:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
 _import_array(void)
 ^
/tmp/easy_install-nawY2E/pyFFTW-0.10.4/pyfftw/pyfftw.c: In function ‘__pyx_f_6pyfftw_6pyfftw_byte_align.isra.48.constprop’:
/tmp/easy_install-nawY2E/pyFFTW-0.10.4/pyfftw/pyfftw.c:2771:6: warning: ‘__pyx_v_update_dtype’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (__pyx_t_1) {
      ^
/usr/bin/ld: //usr/local/lib/libfftw3.a(apiplan.o): relocation R_X86_64_32S against .rodata' can not be used when making a shared object; recompile with -fPIC
//usr/local/lib/libfftw3.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by grlee77** [comment]
I believe pyFFTW is intended to link to dynamic FFTW libraries (base on the output above it has found static libs (e.g. `libfftw3.a`)).  I think you can link to the static libraries if you recompile the static FFTW libraries with the -fPIC flag.

**Comment by hgomersall** [comment]
Yes, as @grlee77 suggests - I think you have an incorrectly compiled FFTW library.

**Comment by spraharsh** [comment]
thanks, I tried compiling fftw from source earlier but using sudo apt-get to find libfftw3-dev was faster
