### ISSUE TITLE
link on github broken

### ISSUE THREAD

**Issue by caseyjlaw** [pyFFTW/pyFFTW#134]
The github description field on this repo refers to documentation at:
http://pyfftw.github.com/pyFFTW/
but the docs are actually at:
http://pyfftw.github.io/pyFFTW.

**Comment by hgomersall** [comment]
Which github description field? Certainly, the README is correct...

**Comment by caseyjlaw** [comment]
I am referring to the first thing someone sees when visiting https://github.com/pyFFTW/pyFFTW. This is the github description field, not a part of the repo.

**Comment by hgomersall** [comment]
Yup, found it. Thanks :)
