### ISSUE TITLE
importing numpy before pyfftw breaks wisdom / planning (really?!)

### ISSUE THREAD

**Issue by zpincus** [pyFFTW/pyFFTW#138]
This seems completely bizarre (and took forever to isolate), but it appears that importing numpy before pyfftw breaks things regarding wisdom and planning. 

Here's a simple test function:
```python
def plan():
    image_arr = pyfftw.empty_aligned(shape=(2560,2160), dtype=numpy.float32, order='F')
    fft_arr = pyfftw.empty_aligned(shape=(2560, 1081), dtype=numpy.complex64, order='F')
    return pyfftw.FFTW(image_arr, fft_arr, axes=(0,1), direction='FFTW_FORWARD', flags=('FFTW_MEASURE',))
```

If I run the following, everything works as expected:
```python
import pyfftw
import numpy

print(pyfftw.export_wisdom()) # not much here
plan() # takes a second or two
print(pyfftw.export_wisdom()) # lots of wisdom
```

**However**, if I merely transpose the two import statements above, things work very differently:
```python
import numpy
import pyfftw

print(pyfftw.export_wisdom()) # some empty strings??
plan() # returns immediately
print(pyfftw.export_wisdom()) # no change
```

First off, the `plan()` function returns way too fast when numpy is imported first. (This is even more obvious if you use the `'FFTW_PATIENT'` flag. If numpy is imported first, the function returns instantly. If numpy is imported second, it takes ~30 minutes, as expected.)

Second, when pyfftw is imported before numpy, the first `pyfftw.export_wisdom()` returns:
```python
(b'(fftw-3.3.4 fftw_wisdom #x3c273403 #x192df114 #x4d08727c #xe98e9b9d\n)\n',
 b'(fftw-3.3.4 fftwf_wisdom #x706526c0 #x2f8b6c85 #x8cd1bb1a #x7c96e03d\n)\n',
 b'(fftw-3.3.4 fftwl_wisdom #x0821b5c7 #xa4c07d5a #x21b58211 #xebe513ab\n)\n')
```

but if numpy is imported first, I get:
```python
(b'',
 b'',
 b'(fftw-3.3.4 fftwl_wisdom #x0821b5c7 #xa4c07d5a #x21b58211 #xebe513ab\n)\n')
```

And after the call to `plan()`, there is no change to the wisdom. (If pyfftw is imported first, calling `plan()` adds a ton of wisdom.)

The `flags` attribute of the FFT returned indicates that the correct flags were used, and the contents of `pyfftw.pyfftw._flag_dict` don't differ if numpy is imported first or second.

As expected, adding the `'FFTW_WISDOM_ONLY'` flag will cause planning to fail in both cases. However, when numpy is imported first (and no wisdom gets created by the planning), it is still the case that a call to `plan()` without the wisdom-only flag will allow a subsequent wisdom-only call to succeed.

This is on ubuntu 16.10 with fftw3 from the ubuntu repository, numpy from anaconda, and the latest pyfftw installed via pip.
```python
In [6]: pyfftw.version.version
Out[6]: '0.10.3.dev0+e827cb5'
In [7]: numpy.version.version
Out[7]: '1.11.2'
```
I cannot replicate this on an OS X machine (same version of pyfftw, and 1.11.1 of numpy, also via anaconda).

I have no idea what's going on here, or how to proceed with debugging this one! If anyone has any ideas, I'll happily run tests until I can figure out what's going on here.

**Comment by zpincus** [comment]
Also, two other observations:
(1) The FFTs computed in each case are very different.
If I run:
```python
fft.input_array.flat = numpy.arange(2560*2160)
val = fft()
```
and save out `val` for the numpy-first vs. pyfftw-first cases, comparing them yields:
```python
In [13]: numpy.abs(val_numpy_first - val_pyfftw_first).max()
Out[13]: 654848.81
```

(2) `pyfftw.import_wisdom()` fails to import wisdom for double and float (corresponding to the empty wisdom strings) if numpy is imported first:
```python
In [15]: pyfftw.import_wisdom([...snip...])
Out[15]: (False, False, True)
```

**Comment by hgomersall** [comment]
Hmmm very odd. I can't reproduce it on my machine. Is this a different manifestation of #40 (MKL symbols treading all over libfftw)? I seem to recall (though couldn't see it on that bug report) that the symbols used depend on the import order.

**Comment by zpincus** [comment]
Yes, it must be the same as #40. I can reproduce the error with the original test case from that bug:
```python
from numpy import empty
from pyfftw.interfaces.numpy_fft import rfft2
rfft2( empty( ( 2, 2, 50, 50 ) ) )
```

The solution (use pyfftw from conda rather than pip) fixes my issue as well.

The issue from #40 has the nice feature of at least breaking in a way that raises an error. Is there any way to make sure that things don't fail silently like they do in the examples above? That seems really pernicious. I only noticed the problem because the planner functions seemed to be running too fast.

**Comment by hgomersall** [comment]
I can't think of a way to error sensibly. I suppose it could check somehow for mkl as opposed to pyfftw. I don't know how to do this reliably - any ideas gratefully received.

**Comment by zpincus** [comment]
I guess it's possible that getting empty double and float wisdom on startup (rather than the default wisdom strings) might be diagnostic? Seems a bit... unprincipled, however.

**Comment by hgomersall** [comment]
It's sort of "not my problem". I do appreciate that lots of people use MKL, but it's distinctly MKL that is causing the problem (and largely because MKL pretends to be API compatible, but actually isn't).

That said, I'm happy to consider pull requests that seek to achieve this. I suspect an empty wisdom string is somewhat brittle and is a pretty weak proxy for mkl being present.

**Comment by zpincus** [comment]
I agree on all counts. I don't have a great solution, and you're right that it's not really pyfftw's problem.
