### ISSUE TITLE
planner effort in the helper interfaces

### ISSUE THREAD

**Issue by anntzer** [pyFFTW/pyFFTW#142]
There is an inconsistency in the docs (https://hgomersall.github.io/pyFFTW/pyfftw/interfaces/interfaces.html#additional-arguments):
> The valid strings, in order of their increasing impact on the time to compute are: 'FFTW_ESTIMATE', 'FFTW_MEASURE' (default), 'FFTW_PATIENT' and 'FFTW_EXHAUSTIVE'.
> The Wisdom that FFTW has accumulated or has loaded (through pyfftw.import_wisdom()) is used during the creation of pyfftw.FFTW objects.
> Note that the first time planning stage can take a substantial amount of time. For this reason, the default is to use 'FFTW_ESTIMATE', which potentially results in a slightly suboptimal plan being used, but with a substantially quicker first-time planner step.

Note the different defaults given in the first and third lines.

It appears that the actual default is `FFTW_MEASURE`.  It would also be nice if it was possible to set thig globally (e.g. `pyfftw.interfaces.set_default_planner_effort("...")`), as this helps for using the common interface in the rest of the code without introducing pyfftw-specific kwargs at each call site.

Likewise, a global setting for the default timelimit would be appreciated.

**Comment by hgomersall** [comment]
Yes, that is an error. Fancy raising a PR? I don't know what the preferred option is - probably to use `FFTW_ESTIMATE` as documented.

On the global setting, I'm weakly resistant to this sort of thing - is a better strategy is to use a lambda in your own code? :
`measuring_fft = lambda x: pyfftw.interfaces.fft(x, planner_effort='FFTW_MEASURE')`

The reason I'm (weakly) resistant is to do with it being IMO bad practice to change global state - it can lead to pretty hard to find bugs because somewhere some code somewhere messes with the module globals.

**Comment by anntzer** [comment]
The problem of FFTW_MEASURE is that it can be very slow on the first run compared to, say, numpy's fftpack.  Of course this is the whole point of FFTW, but this makes the interfaces API more problematic to use as a drop-in replacement of numpy.fft and scipy.fftpack.  So yes I'd favor switching to FFTW_ESTIMATE as default.

The proposed global defaults, likewise, are there to help using the interfaces as a global drop-in replacement.  I think they'd do more good than harm (in fact the only problem I can see is an increase or decrease in performance if someone else messes with the globals, and it should at least be easy to find the bottleneck), but I do understand your point about the risks.

**Comment by hgomersall** [comment]
I understand the issue. I think it _should_ be changed to `FFTW_ESTIMATE`. I'm just very wary of having global state - especially when there is a good alternative. A problem can be in which downstream code breaks upstream code in a non-obvious way leading to a pretty hard-to-find set of issues (why is Jane's installation of pyfoo suddenly running slowly?)

I'll happily accept a PR that changes the default to `FFTW_ESTIMATE`. We need to have more discussion about how to change the default though. Feel free to argue with me.

**Comment by anntzer** [comment]
Let's change it to FFTW_ESTIMATE first -- API to switch the defaults can always be discussed later.

As a comparison point, MATLAB (which also uses fftw) uses FFTW_ESTIMATE by default (https://www.mathworks.com/help/matlab/ref/fftw.html).  Despite all the bad things one can think about MATLAB, they've certainly tried to pick the most "generically user-friendly" option.

**Comment by grlee77** [comment]
I think this issue has been resolved now or is it still open regarding potentially changing the default for the FFTW class itself?

**Comment by jakirkham** [comment]
Good to close?

**Comment by anntzer** [comment]
I think #241 fixes this, if I understood it correctly?

**Comment by grlee77** [comment]
closed by #241 and #148
