### ISSUE TITLE
Auto-allocate output array in FFTW constructor

### ISSUE THREAD

**Issue by anntzer** [pyFFTW/pyFFTW#143]
A minor convenience issue: it would be nice if the `FFTW()` constructor had `output_array` as an optional argument, and allocates itself an array of the correct size and dtype (which are fixed given the input array size and dtype) if `output_array` is not explicitly set.
(Writing the correct shape of the output array is not hard, but a bit lengthy when multiple axes are involved.)

**Comment by hgomersall** [comment]
This is the purpose of the builders. Is there a use case where the builders don't suffice?

To be clear, as implemented, the input array dtypes are not [unique for a transform type](http://hgomersall.github.io/pyFFTW/pyfftw/pyfftw.html).

**Comment by anntzer** [comment]
Ah, sorry, this is a case of me not reading the docs fully.  Perhaps you can add a sentence right after "input_array and output_array should be numpy arrays. The contents of these arrays will be destroyed by the planning process during initialisation. Information on supported dtypes for the arrays is given below." such as
> The builders routines [link to the page] wrap the allocation of the output array based on the input array shape and dtype.

(I see the builders are already mentioned at the top, but that'll help for those like myself just skimming through the call signature...)

Feel free to close the issue.
