### ISSUE TITLE
Invalid Scheme

### ISSUE THREAD

**Issue by seanlaw** [pyFFTW/pyFFTW#145]
According to the docs, I should be able to do this:

    import pyfftw
    a = pyfftw.empty_aligned(10, 'float64')
    b = pyfftw.empty_aligned(10, 'complex128')
    pyfftw.FFTW(a,b)

But I get:

    pyfftw/pyfftw.pyx in pyfftw.pyfftw.FFTW.__cinit__ (/Users/travis/miniconda3/conda-bld/work/pyFFTW-0.10.4/pyfftw/pyfftw.c:9188)()

    ValueError: Invalid shapes: The input array and output array are invalid complementary shapes for their dtypes.

My input to the forward FFT is real dtype.

**Comment by hgomersall** [comment]
Which part of the docs says you can do that? I suggest the following is pertinent:

For a Real transform in the Forwards direction, both the following should be true:

- output_array.shape[axes][-1]
- input_array.shape[axes][-1]//2 + 1

All the other axes should be equal in length.

**Comment by seanlaw** [comment]
I see, so for the 1D array I should've done this instead:

    import pyfftw
    x = 10
    a = pyfftw.empty_aligned(x, 'float64')
    b = pyfftw.empty_aligned(x//2+1, 'complex128')
    pyfftw.FFTW(a,b)

If my input is always real then does it make sense to keep the input dtype as float64 from a speed perspective? In other words, cam I assume that doing real-fft is faster than complex-fft?

**Comment by hgomersall** [comment]
Yes, generally a real FFT is faster than a complex FFT. You can get more speed up by using Float32 if you don't need the full 64 bits of precision.

Powers of 2 definitely speed things up, but then the difference would be less when compared to Numpy (which is actually pretty quick now). You can use the builders to do this automatically if you want - the implementation is pretty optimised (it's all slicing in place) using an FFTW proxy wrapper.

Wisdom is just exported as a tuple of strings, which can be saved as you want (using e.g. pickle).

If you want to squeeze as much performance out as you can you'll need to look at the alignment and also the number of threads used.

It's non obvious how all these various choices interact, so the best option is to test over your various design parameters and see which is fastest (using timeit). I suggest reading _all_ the docs so you understand what's implemented for you - some stuff can use behind the scene automatic optimisations.

**Comment by hgomersall** [comment]
Also, don't always assume a real FFT is faster - try and see.
