### ISSUE TITLE
README on pypi still points to github.com/hgomersall/pyfftw

### ISSUE THREAD

**Issue by anntzer** [pyFFTW/pyFFTW#146]
Last line of https://pypi.python.org/pypi/pyFFTW ("The documentation can be found here, and the source is on github.") has an outdated link (compare with the README in the repo).

**Comment by jakirkham** [comment]
Care to do a PR? Would just be changing this [line]( https://github.com/pyFFTW/pyFFTW/blob/530e400e7c45a8111bf9aec170d10cacb4d0d051/setup.py#L460 )? Though the update won't propagate to PyPI until the next release.

**Comment by jakirkham** [comment]
Also these [lines]( https://github.com/pyFFTW/pyFFTW/blob/530e400e7c45a8111bf9aec170d10cacb4d0d051/setup.py#L219-L220 ) probably should be updated too.

**Comment by anntzer** [comment]
Feel free to pick the issue up.

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/pyFFTW/pyFFTW/pull/156 ).
