### ISSUE TITLE
Add windows wheel for Py3.6 on PyPI

### ISSUE THREAD

**Issue by anntzer** [pyFFTW/pyFFTW#147]
All's in the title; thanks in advance.

**Comment by hgomersall** [comment]
PR welcomed.

**Comment by wtdcode** [comment]
Hope so. :p

**Comment by jakirkham** [comment]
It should happen in the next release, which looks to be soon.

**Comment by JeppeKlitgaard** [comment]
Python 3.6 support has been dropped as far as I can tell. I imagine this issue has just ben forgotten about.

Should this be closed, @hgomersall?
