### ISSUE TITLE
Using OpenMP threads instead of POSIX threads

### ISSUE THREAD

**Issue by zronaghi** [pyFFTW/pyFFTW#174]
Hi all, 

Is there a way to enable OpenMP threads for pyFFTW? 
Looks like if FFTW is compiled with both --enable-threads and --enable-openmp, it links to fftw3_threads. I'm trying to use MPI with OpenMP and also from FFTW docs we might be able to get better performance: http://www.fftw.org/fftw3_doc/Installation-and-Supported-Hardware_002fSoftware.html#Installation-and-Supported-Hardware_002fSoftware

**Comment by hgomersall** [comment]
I don't see why not. Just tweak [`setup.py`](https://github.com/pyFFTW/pyFFTW/blob/master/setup.py#L145). Let me know what happens (though I'd be surprised if you see much change).

**Comment by zronaghi** [comment]
Got it, improved about x1.4 times, thank you!

**Comment by hgomersall** [comment]
That's interesting. Maybe we should enable that as an option. Do you know why OpenMP is faster?

**Comment by grlee77** [comment]
I tried this out on a linux workstation for size 256x256x256 3D FFTN of 64-bit complex data (pre-planned using the builders).  I measured approximately the same times for the OpenMP or pthreads cases (variance across timing runs for the same technique was higher than the difference across techniques).

At first OpenMP was a bit slower, but I found that the OMP_NUM_THREADS environment variable had been set to the number of physical cores so that was preventing hyper-threading.  After increasing OMP_NUM_THREADS to twice the number of physical cores the timings were the same.

**Comment by zronaghi** [comment]
I wrote a simple benchmark for a 1D array and used pyfftw.interfaces.numpy_fft.fft. The times on a Intel haswell for 32 omp threads were around 21 seconds compared to 30 seconds for 32 pthreads 

But mostly we're trying to use OpenMP since the rest of the code uses that and want to avoid any conflicts with pthreads.

**Comment by fredRos** [comment]
In #177 I will add code to detect which libs are available. This would make it easy to add an option to choose which thread lib to link to. I'd prefer the default to be openmp because it's easier to modify from the outside by setting `OMP_NUM_THREADS=4 python ...`

**Comment by hgomersall** [comment]
OpenMP is not the usual build though and needs more dependencies. Posix is ubiquitous and is what FFTW will be linked against by default.

**Comment by hgomersall** [comment]
Oh, I see. Use OpenMP if it's available? That would be fine.

**Comment by fredRos** [comment]
Sure, openmp preferred and posix as fall back.

**Comment by grlee77** [comment]
Closing this as resolved now that #177 has been merged, building with openmp threads is the default with posix threads as a fallback.

In #185, a `PYFFTW_USE_PTHREADS` environment variable is proposed for users that want to override the default behavior and use pthreads instead of openmp.
