### ISSUE TITLE
Dask 2-D/N-D wrappers for pyFFTW

### ISSUE THREAD

**Issue by jakirkham** [pyFFTW/pyFFTW#175]
Currently we have 1-D Dask wrappers for pyFFTW. The recent release of Dask 0.14.2 adds support for wrapping/handling 2-D and N-D arrays with the Dask wrappers. Given this advancement, it would be nice to take advantage of this by providing wrapped version of the pyFFTW 2-D and N-D interface for use with Dask.

Dask 2-D/N-D FFT support: https://github.com/dask/dask/pull/2116

Support for 1-D FFTs with Dask in pyFFTW: https://github.com/pyFFTW/pyFFTW/issues/151 , https://github.com/pyFFTW/pyFFTW/pull/154 , https://github.com/pyFFTW/pyFFTW/pull/166

**Comment by hgomersall** [comment]
This is fixed now?

**Comment by jakirkham** [comment]
Nope. Haven’t added 2-D and N-D wrappers for pyFFTW yet. It’s on my todo list. Just haven’t had time.

**Comment by hgomersall** [comment]
@jakirkham apologies for high-jacking this thread - I just had a couple of requests from github for perms for Appveyor and RTD. Does this relate to an issue? (if not, perhaps you could start one to explain it). Cheers!

**Comment by jakirkham** [comment]
Sorry, I knew I saw this notification somewhere, but somehow lost it. Was recently working on another OSS project that was getting migrated to an org. So was helping set up CI, RTD, etc. and noticed that there were a few things not enabled for pyFFTW at the time. Mostly related to existing services we already use. Though might have added Coveralls (not remembering ATM). Hence the requests sent out for these things. If there is concern about them, happy to chat further, but hope they would be straightforward. It's unfortunate that GitHub doesn't have PM for things like this that are of little general interest and need to be dealt with in semi real time.

**Comment by jakirkham** [comment]
PR ( https://github.com/pyFFTW/pyFFTW/pull/212 ) will address this, but will need to get some test fixes in PR ( https://github.com/pyFFTW/pyFFTW/pull/211 ) merged first.
