### ISSUE TITLE
pyfftw segfaults on import

### ISSUE THREAD

**Issue by olofk** [pyFFTW/pyFFTW#179]
I've tried both the version from pip and building from source, but in both cases I get a segmentation fault as soon as I import pyfftw. Not sure what you need to debug this more. Attachaing the last lines from `strace python -c "import pyfftw"` if that is of any help. Running on Gentoo with Python 3.4, fftw 3.3.4 and numpy 1.10.4

    stat("/usr/lib64/python3.4",` {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    stat("/usr/lib64/python3.4/plat-linux", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    stat("/usr/lib64/python3.4/lib-dynload", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    stat("/usr/lib64/python3.4/lib-dynload/_bisect.cpython-34m.so", {st_mode=S_IFREG|0755, st_size=12544, ...}) = 0
    open("/usr/lib64/python3.4/lib-dynload/_bisect.cpython-34m.so", O_RDONLY|O_CLOEXEC) = 4
    read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200\r\0\0\0\0\0\0"..., 832) = 832
    fstat(4, {st_mode=S_IFREG|0755, st_size=12544, ...}) = 0
    mmap(NULL, 2107968, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f30d03ee000
    mprotect(0x7f30d03f0000, 2093056, PROT_NONE) = 0
    mmap(0x7f30d05ef000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x1000) = 0x7f30d05ef000
    close(4)                                = 0
    mprotect(0x7f30d05ef000, 4096, PROT_READ) = 0
    stat("/home/olof/code/tmp/pyFFTW/pyfftw", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    brk(0x28cc000)                          = 0x28cc000
    brk(0x28f1000)                          = 0x28f1000
    brk(0x2912000)                          = 0x2912000
    brk(0x2937000)                          = 0x2937000
    brk(0x2965000)                          = 0x2965000
    --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xd687f638} ---
    +++ killed by SIGSEGV +++
    Segmentation fault

**Comment by olofk** [comment]
Running with gdb gets me one step further

    (gdb) c
    Continuing.
    
    Program received signal SIGSEGV, Segmentation fault.
    0x00007f248c72bc21 in PyDict_SetItem () from /usr/lib64/libpython3.4m.so.1.0

I guess at this point I should rebuild with debug symbols, but I'm not sure how to do that

**Comment by olofk** [comment]
Just figured out how to get the backtrace :)

    (gdb) bt
    #0  0x00007f907fb9bc21 in PyDict_SetItem () from /usr/lib64/libpython3.4m.so.1.0
    #1  0x00007f907fc28363 in _PyImport_FixupExtensionObject () from /usr/lib64/libpython3.4m.so.1.0
    #2  0x00007f907fc2a60d in _PyImport_LoadDynamicModule () from /usr/lib64/libpython3.4m.so.1.0
    #3  0x00007f907fc27795 in ?? () from /usr/lib64/libpython3.4m.so.1.0
    #4  0x00007f907fc14955 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #5  0x00007f907fc16ef7 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.4m.so.1.0
    #6  0x00007f907fc15011 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #7  0x00007f907fc16ef7 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.4m.so.1.0
    #8  0x00007f907fb89846 in ?? () from /usr/lib64/libpython3.4m.so.1.0
    #9  0x00007f907fb605b8 in PyObject_Call () from /usr/lib64/libpython3.4m.so.1.0
    #10 0x00007f907fc12151 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #11 0x00007f907fc16ef7 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.4m.so.1.0
    #12 0x00007f907fc15011 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #13 0x00007f907fc15430 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #14 0x00007f907fc15430 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #15 0x00007f907fc15430 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #16 0x00007f907fc16ef7 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.4m.so.1.0
    #17 0x00007f907fb89759 in ?? () from /usr/lib64/libpython3.4m.so.1.0
    #18 0x00007f907fb605b8 in PyObject_Call () from /usr/lib64/libpython3.4m.so.1.0
    #19 0x00007f907fb61064 in _PyObject_CallMethodIdObjArgs () from /usr/lib64/libpython3.4m.so.1.0
    #20 0x00007f907fc29984 in PyImport_ImportModuleLevelObject () from /usr/lib64/libpython3.4m.so.1.0
    ---Type <return> to continue, or q <return> to quit---
    #21 0x00007f907fc0c8d8 in ?? () from /usr/lib64/libpython3.4m.so.1.0
    #22 0x00007f907fb605b8 in PyObject_Call () from /usr/lib64/libpython3.4m.so.1.0
    #23 0x00007f907fc0ec17 in PyEval_CallObjectWithKeywords () from /usr/lib64/libpython3.4m.so.1.0
    #24 0x00007f907fc128bb in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #25 0x00007f907fc16ef7 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.4m.so.1.0
    #26 0x00007f907fc16f9b in PyEval_EvalCode () from /usr/lib64/libpython3.4m.so.1.0
    #27 0x00007f907fc0bfca in ?? () from /usr/lib64/libpython3.4m.so.1.0
    #28 0x00007f907fc14955 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #29 0x00007f907fc16ef7 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.4m.so.1.0
    #30 0x00007f907fc15011 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #31 0x00007f907fc15430 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #32 0x00007f907fc15430 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #33 0x00007f907fc15430 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #34 0x00007f907fc15430 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #35 0x00007f907fc16ef7 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.4m.so.1.0
    #36 0x00007f907fb89759 in ?? () from /usr/lib64/libpython3.4m.so.1.0
    #37 0x00007f907fb605b8 in PyObject_Call () from /usr/lib64/libpython3.4m.so.1.0
    #38 0x00007f907fb61064 in _PyObject_CallMethodIdObjArgs () from /usr/lib64/libpython3.4m.so.1.0
    #39 0x00007f907fc29984 in PyImport_ImportModuleLevelObject () from /usr/lib64/libpython3.4m.so.1.0
    #40 0x00007f907fc0c8d8 in ?? () from /usr/lib64/libpython3.4m.so.1.0
    #41 0x00007f907fb605b8 in PyObject_Call () from /usr/lib64/libpython3.4m.so.1.0
    #42 0x00007f907fc0ec17 in PyEval_CallObjectWithKeywords () from /usr/lib64/libpython3.4m.so.1.0
    #43 0x00007f907fc128bb in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
    #44 0x00007f907fc16ef7 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.4m.so.1.0
    #45 0x00007f907fc16f9b in PyEval_EvalCode () from /usr/lib64/libpython3.4m.so.1.0
    #46 0x00007f907fc32af4 in ?? () from /usr/lib64/libpython3.4m.so.1.0
    #47 0x00007f907fc36292 in PyRun_InteractiveOneObject () from /usr/lib64/libpython3.4m.so.1.0
    #48 0x00007f907fc3654e in PyRun_InteractiveLoopFlags () from /usr/lib64/libpython3.4m.so.1.0
    #49 0x00007f907fc36f5e in PyRun_AnyFileExFlags () from /usr/lib64/libpython3.4m.so.1.0
    #50 0x00007f907fc4c1e3 in Py_Main () from /usr/lib64/libpython3.4m.so.1.0
    #51 0x0000000000400b16 in main ()

**Comment by olofk** [comment]
False alarm. Apparenty rebuilding python did the trick for me. Closing now

**Comment by hgomersall** [comment]
Nice :) (self resolving, the best kind of bug report).
