### ISSUE TITLE
pip install pyfftw error in python 2.7 

### ISSUE THREAD

**Issue by basileradisson** [pyFFTW/pyFFTW#180]
Hi,

I can not install pyfftw by using pip with python 2.7 on ubuntu 16.04. Find the log file attached
[log.txt](https://github.com/pyFFTW/pyFFTW/files/1057442/log.txt)

Does somoeone know this issue ?

Thanks in advance

**Comment by hgomersall** [comment]
I don't think you have FFTW installed properly. You need the dynamic libraries to be installed.

**Comment by hgomersall** [comment]
Actually, the static libs might work, but you don't have them installed with fPIC, as pointed out in the log.

**Comment by basileradisson** [comment]
Ok thank you very much and now i have another issue 
[log.txt](https://github.com/pyFFTW/pyFFTW/files/1058724/log.txt)

**Comment by grlee77** [comment]
This looks like you only have the **double** precision FFTW routines and the **single** and **long double** variants are not found.  Currently all three variants must be present (see FFTW docs on how to build each), but there is an open PR #177 to support detecting and using whatever subset is available.

**Comment by grlee77** [comment]
**Re: building the variants**
You can example FFTW build flags for each case here:
https://github.com/conda-forge/fftw-feedstock/blob/8e3ec18d42a949ed93029dfb8d69b7b43fe89060/recipe/build.sh#L35-L39

**Comment by basileradisson** [comment]
Thanks the pip install for pyfftw worked !! But now I have 
File "/usr/local/lib/python2.7/dist-packages/pyfftw/__init__.py", line 16, in <module>
    from .pyfftw import (
ImportError: libfftw3l.so.3: cannot open shared object file: No such file or directory

when i import pyfftw
