### ISSUE TITLE
problems installing on ubuntu

### ISSUE THREAD

**Issue by francispoulin** [pyFFTW/pyFFTW#181]
I am trying to install pyFFTW on a new computer and having some problems.  I did install fftw3 using apt-get.  Any advice as to how I might fix this error?

Thank you in advance.

$ sudo -H pip install pyfftw
Collecting pyfftw
  Using cached pyFFTW-0.10.4.tar.gz
Building wheels for collected packages: pyfftw
  Running setup.py bdist_wheel for pyfftw ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fQRrAa/pyfftw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpkyauonpip-wheel- --python-tag cp27:
  Compiling /tmp/pip-build-fQRrAa/pyfftw/pyfftw/pyfftw.pyx because it depends on /usr/local/lib/python2.7/dist-packages/Cython/Includes/numpy/__init__.pxd.
  [1/1] Cythonizing /tmp/pip-build-fQRrAa/pyfftw/pyfftw/pyfftw.pyx
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pyfftw
  copying pyfftw/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw
  copying pyfftw/version.py -> build/lib.linux-x86_64-2.7/pyfftw
  creating build/lib.linux-x86_64-2.7/pyfftw/builders
  copying pyfftw/builders/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
  copying pyfftw/builders/_utils.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
  copying pyfftw/builders/builders.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
  creating build/lib.linux-x86_64-2.7/pyfftw/interfaces
  copying pyfftw/interfaces/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
  copying pyfftw/interfaces/cache.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
  copying pyfftw/interfaces/_utils.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
  copying pyfftw/interfaces/numpy_fft.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
  copying pyfftw/interfaces/scipy_fftpack.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
  running build_ext
  building 'pyfftw.pyfftw' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/tmp
  creating build/temp.linux-x86_64-2.7/tmp/pip-build-fQRrAa
  creating build/temp.linux-x86_64-2.7/tmp/pip-build-fQRrAa/pyfftw
  creating build/temp.linux-x86_64-2.7/tmp/pip-build-fQRrAa/pyfftw/pyfftw
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-build-fQRrAa/pyfftw/include -I/tmp/pip-build-fQRrAa/pyfftw/pyfftw -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c /tmp/pip-build-fQRrAa/pyfftw/pyfftw/pyfftw.c -o build/temp.linux-x86_64-2.7/tmp/pip-build-fQRrAa/pyfftw/pyfftw/pyfftw.o
  In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                   from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from /tmp/pip-build-fQRrAa/pyfftw/pyfftw/pyfftw.c:462:
  /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  /tmp/pip-build-fQRrAa/pyfftw/pyfftw/pyfftw.c:466:19: fatal error: fftw3.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyfftw
  Running setup.py clean for pyfftw
Failed to build pyfftw
Installing collected packages: pyfftw
  Running setup.py install for pyfftw ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fQRrAa/pyfftw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u3hsst-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pyfftw
    copying pyfftw/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw
    copying pyfftw/version.py -> build/lib.linux-x86_64-2.7/pyfftw
    creating build/lib.linux-x86_64-2.7/pyfftw/builders
    copying pyfftw/builders/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
    copying pyfftw/builders/_utils.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
    copying pyfftw/builders/builders.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
    creating build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/cache.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/_utils.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/numpy_fft.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/scipy_fftpack.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    running build_ext
    building 'pyfftw.pyfftw' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/tmp
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-fQRrAa
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-fQRrAa/pyfftw
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-fQRrAa/pyfftw/pyfftw
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-build-fQRrAa/pyfftw/include -I/tmp/pip-build-fQRrAa/pyfftw/pyfftw -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c /tmp/pip-build-fQRrAa/pyfftw/pyfftw/pyfftw.c -o build/temp.linux-x86_64-2.7/tmp/pip-build-fQRrAa/pyfftw/pyfftw/pyfftw.o
    In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from /tmp/pip-build-fQRrAa/pyfftw/pyfftw/pyfftw.c:462:
    /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    /tmp/pip-build-fQRrAa/pyfftw/pyfftw/pyfftw.c:466:19: fatal error: fftw3.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fQRrAa/pyfftw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u3hsst-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-fQRrAa/pyfftw/

**Comment by grlee77** [comment]
Did you install the fftw3-dev package?  That will be required to get the
headers that the messages here indicate are not being found.

**Comment by francispoulin** [comment]
No I didn't.  Sorry.  When I do it works nicely.

Thanks for the quick and helpful reply!
