### ISSUE TITLE
Dodgy badges?

### ISSUE THREAD

**Issue by hgomersall** [pyFFTW/pyFFTW#191]
Is anyone else getting incorrect badges on the front page github README?

Appveyor is red but clicking through shows it to be all fine (AFAICT).

**Comment by grlee77** [comment]
Yes, I see the same here.  (ReadtheDocs also shows as failed)

**Comment by hgomersall** [comment]
Hmmm I don't know what the problem is with this. I blame appveyor

**Comment by fredRos** [comment]
Yes, I see red badges as well

**Comment by hgomersall** [comment]
Hmm, appveyor is failing now. I can't work out why... These CI tools are really hard to work with!

**Comment by grlee77** [comment]
Appveyor is all green again following #198.  PR #200 should hopefully fix Readthedocs and allow us to close this

**Comment by hgomersall** [comment]
Yeah, I've just merged #200 so hopefully we can close this then. :smile:

**Comment by grlee77** [comment]
Everything is green again.  The failures were real, so I guess having the badges there did at least help in noticing the problem sooner than we would have otherwise.
