### ISSUE TITLE
Build Wheels for Linux and MacOS

### ISSUE THREAD

**Issue by cancan101** [pyFFTW/pyFFTW#193]
Here is another project that had to deal with creating wheels for multiple OS': https://github.com/skvark/opencv-python/

**Comment by jakirkham** [comment]
So one of the other maintainer's and I maintain the `conda-forge` build of this package. Maybe that would work for you?

**Comment by cancan101** [comment]
It's works, but we are  trying to go with a pure pip + pypi install.

**Comment by jakirkham** [comment]
This definitely gets more challenging the further one strays from "normal" Python packages. At least for me personally, I'm not going to take on maintenance of another way to build this or any other library I maintain.

However it might be possible to reuse the conda-forge recipe to get wheels. That would be something I would be open to. If that works for you, then let's give that some thought. If not, then we should discuss what it is you are looking for further.

**Comment by hgomersall** [comment]
Is the point here that we should be building for everything under the sun? I'm slightly confused as to the goal of this issue.

**Comment by cancan101** [comment]
I don' the goal is / should be to build everything under the sun. I do think it reasonable for a project to ship python wheels to pypi as that is the standard way of installing packages in the Python ecosystem.

**Comment by cancan101** [comment]
Would you be open to my PRing wheel building (for linux) to travis?

**Comment by hgomersall** [comment]
Sure!

**Comment by hgomersall** [comment]
It looks reasonable to me. I'd be keen not to have a file called `config.sh` or `run_test.py` - I think they need to be explicitly denoted as relevant to pip. I'm a little wary of including FFTW in the build - IMO this is something that should be handled by the distribution. Is there a reason why it should be part of the pip install?

**Comment by cancan101** [comment]
I'm not sure I follow your concerns. The way this is set up is very similar to how I believe conda forge works in that a pre-built binary is produced including libraries statically linked against fftw. No building occurs when the user pip installs.

**Comment by hgomersall** [comment]
*shrug* I don't really have a strong opinion - I just don't like the bloat very much. The names of the additional files should be changed or moved though if that's possible.

**Comment by cancan101** [comment]
One other comment is that this doesn't have to be pr'ed to the main repos. It can be left as its own repos that gets pin bumped on new release to build wheel and push to pypi.

**Comment by hgomersall** [comment]
That would work. What're the permissions requirements for that?

**Comment by hgomersall** [comment]
It would be nice to have a single PyPI page.

**Comment by cancan101** [comment]
Yes of course, single PyPI page. Assuming you want to keep separate repos, plan would be to transfer this repos to you guys and let you manage the secrets for uploading, etc.

**Comment by hgomersall** [comment]
Yeah, that makes sense. Does it work now? Can you enumerate what needs to be done in order for this to work when transferred? (I mean, what hooks need to be put in place etc - I don't know how to trigger the builds automatically).

**Comment by jakirkham** [comment]
Would you be interested in continuing to maintain this @cancan101?

Not to overstep @hgomersall. Just thinking since @cancan101 knows the most about how this should work and has a vested interest in it, maybe it would make sense to extend membership as well.

Thoughts?

**Comment by hgomersall** [comment]
Yeah, I'm keen for this. It'll be its own repository so should be easy to do.

**Comment by cancan101** [comment]
Yes, I would be interested.
As far as trigger a build, you just push an update to the repos. Right now it is pinned to a specific version of pyfftw in pypi though that can be changed easily to a GH tag, etc.

Right now i have it building for linux 2.7/3.5; easy enough to add more targets. 

Would just need to wire up twine uploads, etc to deploy (assuming we want integrated deploys).

**Comment by jakirkham** [comment]
Yeah configuring uploads is definitely one of those things that will be easier to do with some level of permissions on the repo and CIs as one needs to encrypt tokens/passwords and the like.

**Comment by grlee77** [comment]
@cancan101's approach looks reasonable to me, but I don't have much experience building wheels.

For PyWavelets, @matthew-brett set this up this same sort of approach for us at:
https://github.com/MacPython/pywavelets-wheels
In that case, the wheels get uploaded to wheels.scipy.org.  I'm not sure what the policy is on adding other packages there.  I think PyWavelet wheels were added under that organization mainly because it became a dependency for scikit-image. 

For the last release of PyWavelets, I manually downloaded the wheels from wheels.scipy.org and uploaded to PyPI using twine, but there is also a script at https://github.com/MacPython/terryfy/blob/master/wheel-uploader that could be used to automate that part.

**Comment by jakirkham** [comment]
FWIW [Travis CI]( https://docs.travis-ci.com/user/deployment/pypi/ ) has a way to do this as well.

**Comment by matthew-brett** [comment]
I'm happy to set you up with the Rackspace upload etc.   I've never used the direct PyPI upload because I find it's fairly common to run into trouble with the wheel builds, with one or other matrix entry failing.  In that case it's nice to have an extra step, where you can check all the builds, and maybe do some fixes, before uploading.

**Comment by hgomersall** [comment]
From my perspective, I have no strong opinion on the solution. I'm happy to adopt anything that achieves the desired goal. I do have general preferences though:
1) It doesn't require a load more work - automation is good, simple is good, other people doing it is good.
2) We shouldn't be sprinkling secrets about the place. We can have perms set on travis, but the API keys should be tightly controlled IMO (basically, there should be a somewhat verifiable single route for packages to arrive on PyPI, even if that's automated through Travis, and that should end with as few people responsible as possible).

**Comment by matthew-brett** [comment]
I have no dog in this race - but the system that nearly all other packages I know of us, is the one I described - automated upload to Rackspace, script for download from Rackspace / upload to PyPI.

For automation, the wheel building is automated, and Rackspace upload is automated.  The manual steps are a) checking that all the builds ran correctly b) running the script to do the pypi uploading.

For secrets - the Rackspace API key is encrypted to your repository key (I have to do that, because I have the Rackspace API key).  So the thing that appears in your `.travis.yml` file is not useful to anyone other than your repo running on Travis CI.  The account is a limited upload / download account, that belongs to scikit-learn.  There are about 4 other people who have the unencrypted key, including Olivier Grisel, of scikit-learn.

For the release to pypi, the usual procedure is that the secret exists only on the machine of the person doing the download / upload, usually in their `.pypirc` file.

**Comment by jakirkham** [comment]
As an alternative, one could attempt to build these wheels in conda-forge. Think I'd mentioned that earlier.

We are discussing this option in issue ( https://github.com/conda-forge/conda-smithy/issues/608 ). A couple examples with background are shown in [this comment]( https://github.com/conda-forge/conda-smithy/issues/608#issuecomment-370359867 ). For pyFFTW, in particular, please take a look at PR ( https://github.com/conda-forge/pyfftw-feedstock/pull/16 ), which would build both conda and wheel packages from the same build.

**Comment by cancan101** [comment]
Let me know how you want to proceed. Right now I am able to build wheels for Linux. Shouldn't be too hard to add os x support, but would be good to know if this is a route people are interested in.

**Comment by matthew-brett** [comment]
I bet you'll find it hard to get feedback about wanting macOS wheels.   I suspect what will happen without wheels is that people thinking of using pyfftw will try pip installing it, and it will fail in a confusing way.  It won't occur to them to complain to you about this, they'll just revert to using numpy.fft or whatever.  Whereas if you do have wheels, the installation will work smoothly and they'll start using and depending on it.

**Comment by cancan101** [comment]
My question is how do we want to proceed here as far as building wheels? It looks like wheels are being built for linux right now.

**Comment by matthew-brett** [comment]
I'm a Mac user, so I'd vote for Mac wheels, if they're fairly easy.

**Comment by cancan101** [comment]
I'm not saying no to Mac wheels, I just want to know people are interested in these pypi wheels at all before investing more time in this.

**Comment by hgomersall** [comment]
I have no strong opinion, but will do what I can to integrate this stuff subject to my concerns above. If mac wheels are included, great.

**Comment by matthew-brett** [comment]
As I was saying before, I think you'll find the effect of Mac wheels will be a considerable increase in Mac users over the next year or so, but these users won't yet be subscribed to this issue, so asking here won't give you much information.

**Comment by cancan101** [comment]
I have a PR up: https://github.com/cancan101/pyFFTW-wheels/pull/7 that will push the results to file.io. Ideally this will be changed to different location. I am happy to transfer ownership of the repos, etc to get this moving forward.

**Comment by grlee77** [comment]
It sounds like there is a general agreement that having the wheels is a good thing.  We just need to decide on the implementation and then @hgomersall with have to grant the needed permissions.  Compatibility and potential maintenance burden seem to be the two key features in selecting the mechanism for wheel building.

> Ideally this will be changed to different location.

@matthew-brett had offered to donate space on the scikit-image Rackspace server.  Would that work for you?  (Thanks for your feedback on the issue Matthew!)

@jakirkham  - You also recently generated wheels with upcoming conda-forge tools at conda-forge/pyfftw-feedstock#16.  Are there potential compatibility issues with this approach as opposed to the manylinux/multibuild approach?  I don't understand the relative merits/drawbacks of each approach well enough to judge which is preferable.

**Comment by cancan101** [comment]
>@matthew-brett had offered to donate space on the scikit-learn Rackspace server. Would that work for you? (Thanks for your feedback on the issue Matthew!)

Sounds good to me.

**Comment by jakirkham** [comment]
My understanding is @cancan101's questions are directed at developers (not users). Correct? Maybe that clears up some of the confusion in the past few posts.

As long as someone is maintaining them, am ok with whatever is decided. My preference would be to keep you engaged @cancan101 (assuming you are still interested).

As one of the core members of conda-forge, am interested in seeing closer collaboration between conda and wheel builders. Think both communities have a lot to gain by working together more closely. There has been some interest in this from different people in both communities. Recently have been pushing the idea of building wheels in conda-forge. ( https://github.com/conda-forge/conda-smithy/issues/608 ) That said, it is fair to characterize building wheels in conda-forge as an exploratory exercise. Thus far the results are promising. There are certainly pros and cons of the conda-forge wheel approach.

Some pros include working with the existing conda community, reusing existing infrastructure/recipes, and release processes to make packages. Configuration of CIs to upload (typically a painful process) is all automated in conda-forge and works very nicely (obviously I'm biased ;). We also build for macOS, Linux, and Windows all in one repo, which is very helpful. Anaconda.org is able to host wheels without issues. FWICT @matthew-brett has done similar things with wheels over at MacPython.

The main con would be compatibility on Linux (conda-forge uses CentOS 6 whereas manylinux1 uses CentOS 5). However these are both very old OSes and the main impact would be for legacy clusters or machines that have not upgraded (CentOS 5 EOL was last year). In practice, both builds end up being compatible on a wide range of machines. That said, I'm hopeful that a new manylinux spec would bridge the gap there. Some other changes will impact conda-forge as a whole (e.g. new compilers), but after looking into it, don't see any major impact for pyFFTW specifically.

Hope that covered all of the questions. Happy to answer more should they arise. :)

**Comment by cancan101** [comment]
My question was aimed at the developers here: trying to understand if they like my proposed path forward for building wheels. That being said, I have a PR up with OS X support: https://github.com/cancan101/pyFFTW-wheels/pull/9 and it looks like it was pretty simple to get working.

**Comment by hgomersall** [comment]
If someone tells me what permissions I need to assign to whom and when, then I can make it so.

**Comment by cancan101** [comment]
Ok so the wheels are getting built and deployed to: http://a365fff413fe338398b6-1c8a9b3114517dc5fe17b7c3f8c63a43.r19.cf2.rackcdn.com/

**Comment by matthew-brett** [comment]
Nice. 

That container is also at https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com

- HTTPS is much better for pip'ers.

**Comment by hgomersall** [comment]
Can I link to that on pypi? I mean, I assume it's possible to `pip install` directly from that location?

**Comment by hgomersall** [comment]
Though I guess this limits its value...

**Comment by matthew-brett** [comment]
You can install from there:

```
CDN_URL=https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com
pip install -f $CDN_URL --pre pyfftw
```

There are instructions e.g. [here](https://github.com/MacPython/nipy-wheels#uploading-the-built-wheels-to-pypi) for uploading from Rackspace to PyPI.  I'll put in a PR to add the instructions.  That would surely be worth doing when you do a release.  Maybe you'd consider building wheels for the previous release?

**Comment by matthew-brett** [comment]
See: https://github.com/cancan101/pyFFTW-wheels/pull/16 for PR with README

**Comment by cancan101** [comment]
Okay, wheels are being built and pushed to: https://travis-ci.org/cancan101/pyFFTW-wheels/builds/359503686. 

Not sure who has access to publish these to pypi.

**Comment by matthew-brett** [comment]
Looks like @hgomersall is the only one with permissions for pypi - is that right?

**Comment by grlee77** [comment]
> Looks like @hgomersall is the only one with permissions for pypi - is that right?

I think so. 

If we also add Appveyor ([example appveyor.yml](https://github.com/MacPython/nipy-wheels/blob/master/appveyor.yml)) then that would complete the set of wheels on rackspace.  I'm not sure exactly how @hgomersall built and uploaded the Windows wheels that are currently on PyPI.

**Comment by cancan101** [comment]
so, thoughts?

**Comment by hgomersall** [comment]
Yeah, I like a unified set of builds!

**Comment by jakirkham** [comment]
Maybe we should invite @cancan101 over and transfer the work to the org before asking more? Seems like he’s already done quite a bit of work and it would be nice not to go through configuration pains twice. Would expect moving over the AppVeyor work should be easier then as well.

**Comment by matthew-brett** [comment]
Just to clarify - I took @hgomersall to mean - yes it would be nice to have a unified set of builds from the current wheel-building repo, by adding Appveyor.

For now, given that there are already functional wheels for Linux and macOS, why not keep going with those, maybe adding Windows, until another working solution seems to be better (perhaps conda-forge, at some stage)?

**Comment by hgomersall** [comment]
At one point in the not too distant past we had appveyor building stuff and pushing the result up to bintray. I think that's possibly broken (?) at the moment.

As an aside, I'm confused about the version numbers bintray. It seems to be setting them to 0.10.5 but AFAICT there is not tag for that.

**Comment by matthew-brett** [comment]
@hgomersall - am I right about what you meant earlier about liking a unified set of builds?

**Comment by hgomersall** [comment]
@matthew-brett Yes exactly!

**Comment by jakirkham** [comment]
@hgomersall, would you be able/willing to create a team under `pyfftw` called something (e.g. `wheels` or similar) and invite @cancan101 to join it? This would help us start off the migration process of the existing work at least.

**Comment by jakirkham** [comment]
To better answer the question, admin perms on the repo are needed to add CIs as they add in webhooks to the repo.

**Comment by matthew-brett** [comment]
Just to clarify - I think the current plan is to:

a) get Windows builds going on the pyFFW-wheel repository (and maybe transfer that repository to pyFFTW) and 
b) explore alternative methods of building wheels via conda-forge.

Is that right? 

For a) - I think the main problem was that only @hgomersall can upload wheels to PyPI?   @hgomersall  - do you want to keep it that way, and do the (mostly automated) upload of the wheels yourself, or give - say @cancan101 permission to do the uploads?

**Comment by hgomersall** [comment]
@cancan101 yeah, I think that would be good.

@matthew-brett that sounds reasonable. I'm actually kind of relaxed about the precise approach, but it seems we need to commit to something. I'm a bit time limited at the moment so if people are happy to take on some roles, I'm super keen for that. In view of that, I think I'm happy for someone else to do the uploads.

As always, there is a trust issue in assigning any permissions, but I think that's just something a growing project has to accept (and remain vigilant on).

**Comment by cancan101** [comment]
transfer done: https://github.com/pyFFTW/pyFFTW-wheels

**Comment by jakirkham** [comment]
Great, so @hgomersall I think all that is left is to provide admin privileges to the `CI` team on `pyFFTW-wheels` on [this page]( https://github.com/orgs/pyFFTW/teams/ci/repositories ).

**Comment by matthew-brett** [comment]
Who then can take on the wheel uploading?  Maybe @cancan101 ?

Do you need any help with the Appveyor setup?  I've just done a couple for projects I'm more involved in, like statsmodels and scikit-image.

Where is the previous Appveyor / wheels setup?

**Comment by jakirkham** [comment]
It's integrated into the CI of this repo. So I guess we could break that out. How do you want us to proceed here, @hgomersall?

**Comment by hgomersall** [comment]
It's in the various appveyor files. #224 I think should fix the issue.

**Comment by hgomersall** [comment]
@jakirkham I have no strong opinion about whether the appveyor build stuff is in pyfftw of pyfftw-wheels. The wheels are built as a side effect of the testing, and the testing should stay in the main repository. As to whether that build is replicated or the files copied - it's fine either way.

**Comment by jakirkham** [comment]
> I think I missed something. Could you say what you mean about being integrated into the CI of the repo?

@matthew-brett, ah that was in regards to the Windows/AppVeyor portion. Sorry for the confusion.

> I have no strong opinion about whether the appveyor build stuff is in pyfftw of pyfftw-wheels. The wheels are built as a side effect of the testing, and the testing should stay in the main repository. As to whether that build is replicated or the files copied - it's fine either way.

@hgomersall

👍 for keeping testing here.

IIUC the plan is to have wheel uploads done by `pyFFTW-wheels`. In which case it makes sense to have Windows included along with everything else already over there just for simplicity. Though have no strong feelings about this either.

**Comment by matthew-brett** [comment]
In scientific stuff, I beleive the most common scheme by far, is to have a separate wheel building repository, that also runs the tests.  If the tests pass, the CI uploads the wheels to the Rackspace container, and the release manager or delegate checks the wheels all built correctly, then does a scripted copy from Rackspace to PyPI.   Examples, with instructions at

* https://github.com/MacPython/numpy-wheels 
* https://github.com/MacPython/scipy-wheels

These build for Linux, OSX and Windows.  The https://github.com/pyFFTW/pyFFTW-wheels repo is built on the same [multibuild](https://github.com/matthew-brett/multibuild) machinery (which, I should say, I am mainly responsible for).

The advantage of the separate repo is that you can build / test on a wider range of platforms, without making your normal testing too slow or consuming of Travis (e.g.) resources.

For my own projects, I like to have a build / install / test wheel matrix entry in my normal repo as well, and I also run the wheel-building repository regularly by Travis-CI cron jobs.

**Comment by hgomersall** [comment]
I presume we can still point the badges to the tests and what not, and with hooks it should all work automatically?

**Comment by hgomersall** [comment]
Also, how does this interact with the tests being run on pull requests?

**Comment by matthew-brett** [comment]
I'm afraid I don't know about the badges / hooks.  I'm guessing it would work.

Testing on PRs - with the separate repo scheme, one mode (that I use) is to test the latest commit on the master branch daily or weekly, to screen for problems.  Come the release, I make a separate branch, that points to a named commit I am thinking of tagging.  I trigger that build, and if it's OK, I tag the commit in the main repo, and then build / upload the wheels.

If the main tests are running, as long as you've got reasonable coverage of platforms, you will rarely see specific problems with the wheels, so weekly testing on master is probably OK once you've got everything running.  So, no, I don't know anyone testing full wheel builds for every PR.

**Comment by hgomersall** [comment]
I'm sure it would be possible to get the hooks etc working. We'd need to get the tests run on PRs, which are a requirement for any strategy. No merge should fail and HEAD should always pass (hence CI!).

**Comment by matthew-brett** [comment]
Ouch - getting the tests to run on all PRs is a bit of a barrier.

You only distribute the wheels at release time, including pre-releases.    So, although it would be ideal to test the wheels at each PR, I'd argue it is reasonable to do daily testing on master (and that's what numpy scipy matplotlib etc do).

You could if you like put a whole lot of wheel build test entries into your standard CI setup, but it would slow your testing down a whole lot, and complicate your CI, because you'd have to build the Linux wheels on the manylinux container.

Maybe you could accept a repo that does daily testing on master for now, with a plan to link it up to per-PR testing as soon as possible?

**Comment by cancan101** [comment]
I think the two repo approach now is probably a good start given the reasons above. You can always move to have the first repo create a PR on the second if need be.

While it is possible that something checked in will break the wheel building process, in the short term this seems low risk. Either way it is still a pareto improvement over the status quo where wheels are not continuously built at all in the main CI system.

**Comment by jakirkham** [comment]
Why the complexity? We could build wheels as part of tests here if we want to test them.

**Comment by matthew-brett** [comment]
I was hinting at the complexity above.  For example, numpy builds wheels for 4 varieties of Python 2.7 (32/64 bits, narrow/wide unicode), then the Pythons 3 (32/64 bits).  You then want say 3 macOS wheels (Python 2.7, 3.5, 3.6).  The macOS wheels are not too taxing, but they do slow down your CI because there is only one macOS build at a time, and they tend to be slow to spin up on Travis.  For the multiple Linux wheels, you have build the wheels in a manylinux docker container, then run auditwheel over them.   This is what multibuild automates.  Of course you could have all these wheel builds in your main CI, but it will be slow, and usually unnecessary, because the chances are pretty small on any one commit, that you'll hit a wheel problem when your standard install is OK.

**Comment by jakirkham** [comment]
Sorry should be more clear. What I was objecting to is that we try to coordinate that testing between two repos. We should figure out what testing we want and make sure that is in the right repo in the first place.

Independently there is a question of what things we want to test here. Will happily defer to others on this. Though would suggest not worrying about 32-bit.

**Comment by matthew-brett** [comment]
But you see the point - that it makes sense to do (as Alex put it) pareto testing - test the major platforms on each commit, test the wheel builds daily.   Otherwise the testing matrix become unwieldy, to little extra benefit.

**Comment by hgomersall** [comment]
yeah that's fine. The PRs should basically check that there are no obvious problems (so Python 2, 3 on Linux, Windows is probably enough).

**Comment by cancan101** [comment]
Following up on this, what are the next steps to get the wheels pushed to pypi?

**Comment by cancan101** [comment]
there are wheels in both: https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/ and https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/. Are you asking for me to re-run the build?

**Comment by jakirkham** [comment]
Am asking if you tried to rebuild today, would it work? Actually trying to rebuild is certainly one way to test it. Part of the reason I'm asking this is we would want to be able to build wheels for the new release; so, it would be good to make sure that is possible and iron out any issues that crop up.

**Comment by cancan101** [comment]
build seems to work: https://github.com/pyFFTW/pyFFTW-wheels/pull/21 though deploy only happens on merge.

**Comment by jakirkham** [comment]
Could we also test merging that to see if it can deploy to Rackspace ok?

**Comment by cancan101** [comment]
Looking at the logs: https://api.travis-ci.org/v3/job/396446816/log.txt and the rackspace directory listing: https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/ it seems that the wheel did get published.

**Comment by jakirkham** [comment]
So the only blocker currently is the next release. ( https://github.com/pyFFTW/pyFFTW/issues/187 ) Feel free to contribute to that discussion.

**Comment by jakirkham** [comment]
As we now have the repo for this up thanks to your work @cancan101 and work on the release is under way, would it be alright to close this out?

**Comment by cancan101** [comment]
sure
