### ISSUE TITLE
Conflict with numexpr over numpy version dependency

### ISSUE THREAD

**Issue by sajid-ali-nu** [pyFFTW/pyFFTW#194]
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - numexpr 2.6.2 np112py36_0 -> numpy 1.12*
  - pyfftw -> numpy 1.13*
Use "conda info <package>" to see the dependencies for each package.

```

**Comment by hgomersall** [comment]
Is this conda only?

**Comment by hgomersall** [comment]
Perhaps this is something for @jakirkham ?

**Comment by jakirkham** [comment]
No clue. There really isn’t enough information to go on. Like what channels are used? What does the environment look like? What `conda` is used? OS?

**Comment by sajid-ali-nu** [comment]
It was conda yes, but I should have taken care to post the precise environment. 

Apologies for not doing so. I did a clean reinstall of anaconda and [removed some packages that was deprecated](https://github.com/ContinuumIO/anaconda-issues/issues/7052) and doing so solved this issue as well.
