### ISSUE TITLE
numpy_fft should re-export rfftfreq

### ISSUE THREAD

**Issue by anntzer** [pyFFTW/pyFFTW#206]
Currently, pyfftw.interfaces.numpy_fft does not reexport np.fft.rfftfreq, causing dask.array (which imports dask.array.fft) to fail to import on a pyfftw-patched process:
```
Traceback (most recent call last):
  File "/tmp/test.py", line 3, in <module>
    import dask.array
  File "/usr/lib/python3.6/site-packages/dask/array/__init__.py", line 44, in <module>
    from . import random, linalg, ghost, learn, fft
  File "/usr/lib/python3.6/site-packages/dask/array/fft.py", line 238, in <module>
    @wraps(np.fft.rfftfreq)
AttributeError: module 'pyfftw.interfaces.numpy_fft' has no attribute 'rfftfreq'
```

**Comment by grlee77** [comment]
Thanks for finding this bug.  Apparently `rfftfreq` has existed since numpy 1.8.  This should only take changing a couple of lines in `pyfftw/interfaces/numpy_fft.py` to do the same as for `fftfreq`.  Please make a small PR if interested, otherwise I will plan to do so in the near future.
