### ISSUE TITLE
AppVeyor status in PRs

### ISSUE THREAD

**Issue by jakirkham** [pyFFTW/pyFFTW#215]
Would be nice if we could include the AppVeyor status in PRs. Not sure if there is a reason not to or if it's just some configuration issue. In any event, would be very helpful to see the progress for each PR more clearly and catch issues raised ahead of time.

**Comment by hgomersall** [comment]
Is this possible? How to do it...?

**Comment by jakirkham** [comment]
Not sure how it isn't enabled by default. Maybe something got messed up on AppVeyor's end? Seems to be a common problem unfortunately. [This advice]( https://help.appveyor.com/discussions/problems/5147-appveyor-build-status-does-not-automatically-show-on-github-pr#comment_43867686 ) seemed to help some people. Might be worth trying?

**Comment by hgomersall** [comment]
Euch, it doesn't seem simple at all! I have to fiddle with the appveyor.yaml or something...

**Comment by jakirkham** [comment]
I hope not. At least that wasn't my read of it.

If you want, I can take a look, but think I need admin permissions to see the webhooks on this repo/(re)authorize services.

Alternatively we can try and ask someone from AppVeyor to help.

**Comment by hgomersall** [comment]
I found this: https://www.appveyor.com/docs/notifications/#github-pull-request I don't know what the token is for the appveyor bot though... Those docs are really limited.

**Comment by jakirkham** [comment]
Have you tried accepting the `AppVeyor CI` application in `Authorized OAuth Apps`? Should be able to do this from your GitHub user settings page.

**Comment by hgomersall** [comment]
It's all there. I'll try to work it out at some point. Appveyor is a PITA.

**Comment by jakirkham** [comment]
So there's the `AppVeyor` application and the `AppVeyor CI` application. Think we need both. Sorry if that's already obvious.

**Comment by hgomersall** [comment]
Yup, got them both...

**Comment by hgomersall** [comment]
Hmm, there was some secret approval I had to grant (from you). Perhaps it will work now...

**Comment by jakirkham** [comment]
That did it. Thanks @hgomersall. :)

ref: https://github.com/pyFFTW/pyFFTW/pull/217
