### ISSUE TITLE
Normalisation with insufficient precision

### ISSUE THREAD

**Issue by wucknitz** [pyFFTW/pyFFTW#222]
The normalisation is not always computed with sufficient precision when using (long) double transforms. 

In pyfftw.pyx the factor is determined as follows:

self._normalisation_scaling = 1/float(self.N)

Whenever 1/N cannot be represented as 32-bit float (typically happens for N not a power of 2), this is not sufficient for double-precision (or higher) transforms.

**Comment by hgomersall** [comment]
float in python is 64-bit.

**Comment by wucknitz** [comment]
Thanks, you are right, of course. I do in fact _have_ the problem that the normalisation of the result is off by exactly the ratio between the 32-bit version of 1/N and the true value, but the reason must be something else. I tried it again on another machine with a clean install of the newest pyfftw and fftw, and there it works fine.
