### ISSUE TITLE
Windows build fails using PyPi

### ISSUE THREAD

**Issue by zfphil** [pyFFTW/pyFFTW#228]
Latest windows build fails when installing latest version. Looks like the PyPi version has some absolute paths in SOURCES.txt. Removing these seems to work.

My system:

```python
>>> platform.platform()
'Windows-10-10.0.16299-SP0'
````

```bash
python --version
Python 3.6.4 :: Anaconda, Inc.
```

FIX:
1. Download package using pip `pip download pyfftw`
2. Change to pyfftw directory (Placed on my desktop by default)
3. Unzip pyFFTW-0.10.4.tar.gz
4. cd ./dist and unzip pyFFTW-0.10.4.tar
5. cd ./pyFFTW-0.10.4/pyFFTW.egg-info
6. open SOURCES.txt (using notepad++ or similar)
7. Change:

```
/home/whg/Projects/github/pyFFTW/pyfftw/pyfftw.c
/home/whg/Projects/github/pyFFTW/pyfftw/pyfftw.pyx
/home/whg21/Projects/github/pyFFTW/pyfftw/pyfftw.c
/home/whg21/Projects/github/pyFFTW/pyfftw/pyfftw.pyx
```

to:

```
pyfftw/pyfftw.c
pyfftw/pyfftw.pyx
pyfftw/pyfftw.c
pyfftw/pyfftw.pyx
```

8. Change to one level above main directory (`cd ../..`)
9. Run `pip install .\pyFFTW-0.10.4`

Make sure the FFTW .dll files are in the correct directory!

Hope this is helpful. I couldn't find the file on github and am not familiar with building for PyPi, but this hack seemed to work for me :D

**Comment by grlee77** [comment]
The issue with absolute paths has been fixed in release 0.11.1 (see #250)

Windows wheels (64-bit) are also available which should make compiling unnecessary.
