### ISSUE TITLE
License is misleading; programs using pyFFTW still need to comply with the GPL

### ISSUE THREAD

**Issue by brakhane** [pyFFTW/pyFFTW#229]
pyFFTW claims to be licensed under 3-clause BSD, however, for pyFFTW to do anything, it needs to use the FFTW library, which is GPL licensed. Therefore, [any program using it must also be GPL licensed](https://www.gnu.org/licenses/gpl-faq.en.html#GPLWrapper), unless they buy a license from MIT.

To avoid people unintentionally violating the FFTW license, I suggest to add a clarification at the beginning of the license and in the documentation that every program using it must effectively be released with the GPL license (unless a license is purchased from MIT)

**Comment by hgomersall** [comment]
This is actually a very grey area when it comes to Python, but I'm actually happy with the principle. A pull request as a clarification to LICENSE would be appreciated.

**Comment by brakhane** [comment]
> This is actually a very grey area when it comes to Python

not sure what it has to do with Python and why it's a grey area.

Created a PR

**Comment by mreineck** [comment]
I think this is a misinterpretation of the linked FAQ.

pyFFTW can be licensed under BSD terms, and any code using pyFFTW can be licensed in that way as well. ONLY if you distribute a "combined package" (e.g. in form of a binary distribution), the whole thing must be covered by GPL terms. But even then nobody is stopping you from distributing the pyFFTW sources additionally under a BSD license.

**Comment by hgomersall** [comment]
I'm confused as the the confusion...

**Comment by mreineck** [comment]
Sorry ... I just encountered this issue while looking for other pyfftw-related information.

I just wanted to clarify the original statement:

> Therefore, any program using it must also be GPL licensed, unless they buy a license from MIT.

To the best of my knowledge this is not correct. The correct statement would be:

"Therefore, any program using it must also have a GPL-commpatible license, unless they buy a license from MIT."

And BSD is GPL compatible.

**Comment by hgomersall** [comment]
I'm happy with that - it's the mechanism under with pyfftw is licensed. Are you able to raise such a PR?

**Comment by brakhane** [comment]
According to [the GPL faw](https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean), "compatible" means that you can combine a compatible licensed program with a GPL program, *however* if you distribute the resulting program, you have to license it using the (same) GPL license.

**Comment by hgomersall** [comment]
Right, but it's possible to distribute the code that is not linked to the GPL code under a more liberal license. "compatible" means you can re-license under the GPL as necessary.

**Comment by brakhane** [comment]
I disagree, however IANAL.

The proposed change of wording is:

> If you intend to **distribute code that makes use of the GPLed FFTW3 library**,
GPL licensed. If you do not wish to comply with the terms of the GPL,
**your code must be released under a GPL-compatible license**

(relevant part highlighted)

The FAQ is pretty clear that this is not allowed:

> All GNU GPL versions permit such combinations privately; 

is not relevant, since we are talking about distribution. So:

> they also **permit distribution** of such combinations **provided the combination is released under the same GNU GPL version.**

So, if I want to distribute code that uses the GPLed version, I have to license under the GPL.

If I distribute code without using the GPLed FFTW (so basically have the user decide which version to use), I can do with a compatible license. (But should include a similar warning as a courtesy)

So as #239 is currently written, it's misleading. The only way to use a compatible license is to not depend on the GPL part (like pyFFTW itself)

**Comment by mreineck** [comment]
I agree 100% with you both :)

The crucial question is what "resulting program" means; I actually had an email exchange with FSF people about this, and they state that the "resulting program" is the result of linking the original code and your own code together, i.e. something binary. If you simply distribute your sources, you are under no obligation to use GPL on them.

If that was not the case, pyfftw could itself not be distributed under BSD terms, wouldn't you agree?

**Comment by mreineck** [comment]
> So, if I want to distribute code that uses the GPLed version, I have to license under the GPL.

Example: if I write a C file that includes the FFTW header and makes a few calls into the FFTW ... ist that a "code that uses the GPLed version of the FFTW"? How can anyone tell? The code does not specify that.

User A might download the code and link it with his copy of the FFTW that he obtained under GPL.

User B migth download it and link it with a copy he obtained under a proprietary license.

The point is that my C file does not express an _intention_ how it might be used. So for a source file it is simply unspecified whether it is a "code that uses the GPLed version of the FFTW".

**Comment by mreineck** [comment]
Just to be clear, IANAL either ;)

**Comment by brakhane** [comment]
Your code uses the GPL version if you include the GPLed FFTW files in your distribution.

Which is what 

> If you intend to distribute code that makes use of the GPLed FFTW3 library, [...]

is about.

For this reason, I find my original text 

> If you intend to use the GPLed FFTW3 library, your code must also be GPL licensed.

clearer and less likely to be misinterpreted.

So, if we want to improve the current clarification, it should be something like:

* just distribute code that requires the user to decide which FFTW library he wants → any license, even proprietary (MIT license)

* distribute code or a program that uses the GPLed FFTW library → GPL

So we either have "any license" or "GPL", mentioning GPL compatible licenses is even more misleading, IMO

**Comment by mreineck** [comment]
I copy below the response I got from FSF when I asked about this topic a few years ago.
Again, this is not legal advice....

--

Hi Martin,

> as a co-author of the GPL Healpix library
> (http://sourceforge.net/projects/healpix) I would like to request your
> advice in a licensing issue. To the best of my knowledge, my concrete
> question has not been addressed in the GPL FAQ (at least not very
> explicitly); if I have missed anything and it has already been
> discussed, I would be glad if you could give me a pointer!
>
> The Healpix library was released under GPL (v2 or later) roughly ten
> years ago, and I am personally very happy with the license.

Thank you for choosing the GPL!

> However, in the last few years we have been getting (with increasing
> frequency) requests to consider re-licensing under more liberal terms
> (e.g. LGPL or BSD-like). These requests originate mostly from Python
> developers, where the software ecosystem appears to be dominated by
> BSD-licensed code.
> Their concern is that whenever they develop a code which makes use of
> Healpix, they are obliged to choose GPL (and only GPL) for their code if
> they want to redistribute it, since it constitutes a "derivative work".
>
> My personal understanding is that these developers have to distribute
> their code under GPL whenever they distribute it as a combined work
> (e.g. as an executable that links, statically or dynamically, against
> Healpix), but that they are free to choose any other GPL-compatibe
> license whenever they simply distribute the sources of their own code.
> This is an interpretation I derived from
> https://www.gnu.org/licenses/gpl-faq.en.html#LinkingWithGPL.
>
> Could you please comment whether my understanding of the situation is
> correct?

That's correct. They can use another GPL-compatible license for their
own code. When they distribute their code with yours, the terms of the
GPL apply to the project as a whole, but anybody is free to extract the
permissively-licensed code and use it elsewhere under that more lax license.

> If it is, I think it would be very helpful to state this in very
> explicit terms in the GPL FAQ (by using a concrete example), since it
> does not appear to be obvious to most people reading it.
> Also I must admit that the use of the word "proprietary" in the FAQ
> entry ("You have a GPL'ed program that I'd like to link with my code to
> build a proprietary program.") seems confusing to me. Perhaps it could
> be replaced by "non-GPL"?
>
> I am quite sure that this issue is of fairly broad interest, since quite
> many developers of GPL libraries find themselves in a comparable
> situation, i.e. they are urged to change to BSD or similar because
> otherwise BSD-licensed supposedly cannot use their libraries.
>
> If it is any help, I am willing to submit a tentative patch for the
GPL FAQ!

We would be happy to review your patch to make this clearer. It would be
bad if authors of GPL libraries felt obligated to re-license in order to
accommodate users of permissive/lax licenses.

Francois

-- 
I am not a lawyer and this is _not_ legal advice.

**Comment by ashwinvis** [comment]
Not a legal advice, but to add to the discussion according to [FFTW FAQ](http://www.fftw.org/faq/section1.html):

>  We could instead have released FFTW under the LGPL, or even disallowed non-Free usage. Suffice it to say, however, that MIT owns the copyright to FFTW and they only let us GPL it because we convinced them that it would neither affect their licensing revenue nor irritate existing licensees. 

So my understanding is ([according to this presentation](https://cicero.xyz/v2/remark/github/coderefinery/software-licensing/master/talk.md/#23)) you are only allowed to link and have a different license if FFTW was LGPL licensed, which is not the case.

**Comment by egpbos** [comment]
In my [code](https://github.com/egpbos/barcode), which is in a similar situation, I have added the following statement to my README's license section:

> The original contributions made as part of this code are distributed under the MIT license (see LICENSE file).
> 
> When compiled, this code must link to FFTW 3 and the GNU Scientific Library (GSL). FFTW is distributed under the GNU Public License v2 or a later version, GSL under GPL v3. This means that any redistribution of Barcode in binary form is subject to GPL v3 terms.

I think this essentially agrees with @mreineck's interpretation.

I think the difference between "code" and "binary" is quite important to make in this.

"Code", as I would define it, is the stuff you, the author, wrote. You therefore own the *copyright* and you therefore decide how you distribute it and under which license.

Only when you distribute a binary version that has been linked to GPL'ed code (and in which you probably included the `fftw3.h` header file, thus compiling GPL'ed code into your binary) you have to distribute it under GPL.

**Comment by moorepants** [comment]
I came across this issue because I have also struggled figuring out how conda packaged binaries that dynamically link to FFTW should be licensed. I still don't have a definitive conclusion but thought that others may want to read some similar conversations:

- https://github.com/SHTOOLS/SHTOOLS/issues/227
- https://github.com/conda-forge/pyshtools-feedstock/issues/3
- https://github.com/conda-forge/openmm-feedstock/issues/24
- https://github.com/conda-forge/conda-forge.github.io/issues/1065

**Comment by ashwinvis** [comment]
@moorepants See the interpretation by the FFTW author, https://github.com/JuliaMath/FFTW.jl/pull/41#discussion_r141968395 which makes a distinction between source archives and binaries.

**Comment by moorepants** [comment]
Thanks, that's helpful.

**Comment by chrisvalx** [comment]
pyFFTW currently has a clear note at the top of its [license](https://github.com/pyFFTW/pyFFTW/blob/master/LICENSE.txt) explaining the different licensing possibilities, so I think this issue has been successfully resolved and can be closed.

**Comment by hgomersall** [comment]
Thanks!
