### ISSUE TITLE
Missing msvcr90.dll / DLL initialization routine failed

### ISSUE THREAD

**Issue by xdxita** [pyFFTW/pyFFTW#232]
Using Python 2.7.10 on win7 sp1 x64
This is the python included on GnuRadio package for windows, PyFFTW installed without issues but once I try to "import pyfftw" I receive this error

> ImportError: DLL load failed: The specified module could not be found

Using Dependency walker I've found that pyfftw.pyd tries to load a missing msvcr90.dll
![image](https://user-images.githubusercontent.com/8539852/43154881-3584b3fe-8f4c-11e8-9042-8452da55e646.png)

If I try to manually add the missing DLL to any search path directories the error message changes to:
![image](https://user-images.githubusercontent.com/8539852/43155067-ba5d49ce-8f4c-11e8-93e9-d0899a6c737c.png)
And the prompt output is:

> importerror dll load failed a dynamic link library (dll) initialization routine failed
Both error comes from:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Program Files\GNURadio-3.7\gr-python27\Lib\site-packages\pyfftw\__init__.py", line 16, in <module>
    from .pyfftw import (`

Not sure if both errors are related to the msvcr90.dll

Tried to search for a similar issue, but nothing.

**Comment by xdxita** [comment]
Reinstalling Python solved the issue.

**Comment by hgomersall** [comment]
good news!
