### ISSUE TITLE
a problem installing pyfftw

### ISSUE THREAD

**Issue by gtmasur** [pyFFTW/pyFFTW#236]
I have downloaded fftw-dev (fftw 3.3.8) in /usr/local/ on Fedora 28. Now, trying to download pyfftw. Let me note that I could not grab the difference between pyfftw and pyfftw3 clearly, so just trying for pyfftw. 
Is there any comment how to deal with the following error? 
Thanks in advance.

$ pip install pyfftw
Collecting pyfftw
  Using cached https://files.pythonhosted.org/packages/c2/2e/b25edc6960fc837e915eb1b38e5f0e3013e32e90aff14a1d0f4556b3d145/pyFFTW-0.10.4.tar.gz
Installing collected packages: pyfftw
  Running setup.py install for pyfftw ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-AcUoBm/pyfftw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2bn2Yj-record/install-record.txt --single-version-externally-managed --compile:
    Compiling /tmp/pip-build-AcUoBm/pyfftw/pyfftw/pyfftw.pyx because it depends on /usr/lib64/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd.
    [1/1] Cythonizing /tmp/pip-build-AcUoBm/pyfftw/pyfftw/pyfftw.pyx
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pyfftw
    copying pyfftw/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw
    copying pyfftw/version.py -> build/lib.linux-x86_64-2.7/pyfftw
    creating build/lib.linux-x86_64-2.7/pyfftw/builders
    copying pyfftw/builders/builders.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
    copying pyfftw/builders/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
    copying pyfftw/builders/_utils.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
    creating build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/_utils.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/cache.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/numpy_fft.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/scipy_fftpack.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    running build_ext
    building 'pyfftw.pyfftw' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/tmp
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-AcUoBm
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-AcUoBm/pyfftw
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-AcUoBm/pyfftw/pyfftw
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/tmp/pip-build-AcUoBm/pyfftw/include -I/tmp/pip-build-AcUoBm/pyfftw/pyfftw -I/usr/lib64/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c /tmp/pip-build-AcUoBm/pyfftw/pyfftw/pyfftw.c -o build/temp.linux-x86_64-2.7/tmp/pip-build-AcUoBm/pyfftw/pyfftw/pyfftw.o
    In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816,
                     from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from /tmp/pip-build-AcUoBm/pyfftw/pyfftw/pyfftw.c:598:
    /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^~~~~~~
    gcc -pthread -shared -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld build/temp.linux-x86_64-2.7/tmp/pip-build-AcUoBm/pyfftw/pyfftw/pyfftw.o -L/usr/lib64 -lfftw3 -lfftw3f -lfftw3l -lfftw3_threads -lfftw3f_threads -lfftw3l_threads -lpython2.7 -o build/lib.linux-x86_64-2.7/pyfftw/pyfftw.so
    /usr/bin/ld: cannot find -lfftw3f
    /usr/bin/ld: cannot find -lfftw3l
    /usr/bin/ld: cannot find -lfftw3_threads
    /usr/bin/ld: cannot find -lfftw3f_threads
    /usr/bin/ld: cannot find -lfftw3l_threads
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-AcUoBm/pyfftw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2bn2Yj-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-AcUoBm/pyfftw/

**Comment by hgomersall** [comment]
Yes, you need to install libfftw.

**Comment by hgomersall** [comment]
Ok, well your error message is because it can't find the libraries. They need to be installed in your normal library search path. Perhaps check they are there.

Also, have you installed all the versions?  (e.g. the float version)

**Comment by hgomersall** [comment]
I think you need to do it for each of the versions - I suggest reading the FFTW libs thoroughly to understand.

The issue also might be because /usr/local is not in your library search path (but I'd check the initial route first).

Is there a reason why you're not installing from the repos? My experience is that FFTW is a bit of a pain to install with all the right optimizations turned on and get it to run as fast as it might.

**Comment by gtmasur** [comment]
I have tried to get fftw from the repos but I failed except this time. In a case that one may benefit, I am writing:
# to see the available version and download
$yum search fftw  
$yum install sudo yum install fftw-devel
then smoothly install pyfftw with 
$sudo pip install pyfftw.

Thanks a lot for all your comments.

**Comment by hgomersall** [comment]
So all is fixed?

**Comment by gtmasur** [comment]
Yes, thanks a lot.
