### ISSUE TITLE
Sniffer on Windows Can't find Files

### ISSUE THREAD

**Issue by psavery** [pyFFTW/pyFFTW#266]
Hi there,

When I follow the instructions for building pyFFTW 0.11.1 on Windows (using Visual Studio 2015), I get complaints from the environment sniffer like the following:
```
error: Could not find the FFTW header 'fftw3.h'
error: Could not find any of the FFTW libraries
```

The problem is that all of the files are in place. And they all *can* be found. The way I have been fixing this issue is by commenting out those checks in the setup.py. When I do that, pyFFTW can compile and install just fine.

Maybe you should add an option to turn off the sniffers? They seem to be causing me trouble at least, when it seems like they shouldn't be producing errors (note that I don't have this issue for pyFFTW 0.10.4).

~~I also ran into a similar problem for MacOS for our automated builds. Our automated build currently builds pyFFTW 0.10.4 without any issues, but if I keep everything in place and try upgrading to pyFFTW 0.11.1, I start getting sniffer errors similar to the above.~~

**Comment by psavery** [comment]
Scratch that last paragraph on MacOS. That one was due to me not having libraries in the right place. But the Windows issue still remains.

**Comment by hgomersall** [comment]
I think commenting them out is a reasonable work around. If you feel enthusiastic, you can try to establish why the problem occurs, but windows is a broken mess IMO when it comes to compiling software.

**Comment by David-Baddeley** [comment]
I'm getting a similar problem and commenting in the hopes that this helps track it down.

Do you get a 
`[WinError 6] The handle is invalid`
somewhere around there? `has_header()` would seem to try and create a c file which includes the header and then compile it, and anything that breaks this process would cause it to behave as though it couldn't find the file.

In my case I've tracked it down to something going wrong with the IO redirection started by the `with stdchannel_redirected(...)` stuff (lines 442 and 458 in setup.py). Commenting the IO redirection out makes it work for a simile `setup.py build` but not when building a conda package.

**Comment by ethanbb** [comment]
@hgomersall It looks like you've made a number of comments to this effect on various issues Windows users have encountered. I submit that this is an unprofessional attitude. Part of the deal when maintaining a cross-platform package, especially if it is the most widely-used of its type, is making sure there is at least a working "happy path" on all platforms. Is it too much to ask to put step-by-step instructions on how to get it up and running on Windows in the README (specifically, where to put the FFTW files after downloading so they can be found during installation)?

**Comment by hgomersall** [comment]
There was a brief comment here from, I think, @ethanbb which asked me why it was appropriate for this bug to exist at all. I'm going to reply to this even though it was removed in the hope that he and others can realise the constraints we operate under, and perhaps entreat others to contribute in preference to criticising.

Firstly, none of the contributors to pyFFTW are paid and I have not received a single penny in recompense for my work on it (which amounts to thousands of hours). I have a full time job and a family that take up pretty much all my time. I don't even use pyFFTW all that much in my work. That said, I do understand the frustration when stuff does not work properly.

In good faith, I suggest that open source projects work best when people contribute solutions themselves. I feel the project strives to be open to new contributors and I think I speak for all the maintainers in saying we would welcome a fix to this problem.

For my part, I have no working Windows installation, so lack the basic tools to actually fix this issue. That means, if someone has the means and the impetus to fix it then they have to take the lead on it, and I will support them as far as I can.

It's also worth noting that as far as I am concerned, my support obligations extend only as far as any other software you can download, which is to say at providing a functioning binary. We provide those on PyPI for releases, as well as on bintray _for every merge_. If that's not enough for you, then please feel free to work on fixing any problems you encounter and we will gratefully accept the resultant pull requests.

I should probably take the opportunity to thank those that have done far more than me in recent years on pyFFTW, notably @grlee77 for doing most of the thankless maintenance tasks.

**Comment by ethanbb** [comment]
Sorry for my inappropriate comment which I then removed.

I just want to report the trouble I had with this, both when using `pip install pyfftw` and installing the wheel directly. Log file attached. Specifically I kept getting the message "Could not find any of the FFTW libraries." I tried putting them in `bin` under my root Python folder and in a folder specified by the  `PYFFTW_LIB_DIR` environment variable. But apparently this shouldn't even be necessary?

This was with Python 3.8, if that's relevant. I wanted to try with 3.7, but at that point I decided to switch to Anaconda instead which worked perfectly.

[pyfftw_install.log](https://github.com/pyFFTW/pyFFTW/files/4740637/pyfftw_install.log)

**Comment by hgomersall** [comment]
In the case of @ethanbb, the problem seems to be that pip is grabbing the source distribution rather than the compiled version. Is this on a 32-bit python installation?

**Comment by ethanbb** [comment]
Ah, turns out yes it was. That seems to be the default download for Windows on python.org/downloads.

**Comment by hgomersall** [comment]
Probably we should be more explicit that we don't support 32-bit any more...

**Comment by IvanOstr** [comment]
I have exactly the same problem. I found out by debugging that the command line argument with cl.exe and linker.exe are broken in windows and doesn't have  " " around the commands which makes this error. I fixed that locally but there are more errors. Did someone managed to fix this?

**Comment by hgomersall** [comment]
@IvanOstr out of interest, why are you trying to build yourself?

**Comment by IvanOstr** [comment]
Ok so after 7 hours of struggling I found out that there were 2 problems - 32 bit as you said above, and python 3.9 as you just posted on the forum. Please save hours of work for the next people and write it in the opening page :)

To answer your question, I debugged setup.py since the error "couldn't find fft3.h" was not very helpful. So I checked the cmd line you run there when you call compiler.compile and it was something like this " C:\bla bla\cl.exe --arguments --I include dirs". the problem was there because when I ran it in the cmd it didn't work. So I fixed the paths to include " " around them (you must have " " around paths in cmd command lines). Problem is there were some other errors too.

Anyway, thanks for commenting above and supporting this library!

**Comment by hgomersall** [comment]
> Please save hours of work for the next people and write it in the opening page :)

We're fighting against continuously moving goal posts! If you'd like to submit a PR to the README that clarifies some of these issues, then it would be gratefully received. I suggest pointing out some of the potential pitfalls "32-bit not supported, check the pre-compiled python versions".

**Comment by JeppeKlitgaard** [comment]
This should have been solved by the `setup.py` changes in #323.

This can be closed now.
