### ISSUE TITLE
Add a scipy.fft interface

### ISSUE THREAD

**Issue by grlee77** [pyFFTW/pyFFTW#268]
Upcoming SciPy 1.4 will have a new `scipy.fft` module that is based on [pypocketfft](https://gitlab.mpcdf.mpg.de/mtr/pypocketfft). While `scipy.fftpack` will stick around, new code is encouraged to use `scipy.fft` which has some nice features as described in the following release note:
https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.4.0#scipyfft-added

see PRs:
scipy/scipy#10238
scipy/scipy#10361

As part of this effort, SciPy will also be gaining an official mechanism to allow setting different backends for the FFT computations. This will allow third party libraries like pyFFTW to define their own `scipy.fft`-compatible backend, removing the need for hacks like monkey patching:
scipy/scipy#10383
Peter (@peterbell10) will likely make a PR to pyFFTW in the near future with a draft of a scipy_fft interface

**Comment by grlee77** [comment]
@peterbell10: Now that scipy/scipy#10383 has been merged, is the plan to open a separate PR to add a `PyfftwBackend` class to this repo? Once that has been done we can point other FFT libraries to it as an example. 

Also, if I understand correctly, adding scipy.fft-compatible backend classes to downstream projects like PyFFTW will not require adding a `uarray` dependency to those projects?

**Comment by peterbell10** [comment]
I was thinking we could just define `__ua_domain__` and `__ua_function__` at the module level. That means the user should be able to do
```python
from pyfftw.interfaces import scipy_fft
import scipy.fft

with scipy.fft.set_backend(scipy_fft):
  scipy.fft.fft([1])
```

I was going to do that in this PR but can split them if you prefer.  I also was thinking of adding a CI check with a pre-release scipy wheel so we can actually test that it's working.

**Comment by grlee77** [comment]
> I was going to do that in #269 but can split them if you prefer. 

No, I am fine with it being in one place. 

> I also was thinking of adding a CI check with a pre-release scipy wheel so we can actually test that it's working.

Yeah, that is probably the best to test it for now (not sure on the anticipated date for a scipy 1.4, but it is probably still a ways off).
