### ISSUE TITLE
missing float and long-double libraries

### ISSUE THREAD

**Issue by aberndsen** [pyFFTW/pyFFTW#27]
Similar to the issues in
https://github.com/hgomersall/pyFFTW/issues/16

It would be nice to remove the dependencies on the long-double fftw3l (or single fftw3f) libraries. Or, at least provide a description on how to get pyfftw to work if these libraries are missing (not compiled). I suppose the current solution is to compile fftw3 with both the single and long-double options. Correct?

**Comment by jakirkham** [comment]
This was solved with PR ( https://github.com/pyFFTW/pyFFTW/pull/189 ), correct @fredRos? If so, think we should close.

**Comment by fredRos** [comment]
Yes, just about 4 years later this issue is solved

**Comment by jakirkham** [comment]
Thanks. :)
