### ISSUE TITLE
Plan for dropping Python 2.7 support

### ISSUE THREAD

**Issue by grlee77** [pyFFTW/pyFFTW#270]
We should specify a plan for dropping Python 2.7 support. 

Numpy [dropped support](https://docs.scipy.org/doc/numpy-1.14.2/neps/dropping-python2.7-proposal.html) for 2.7 (and 3.4) in new releases starting at the beginning of 2019 and have only committed to making bug fixes to the 1.16.x branch supporting Python 2.7 until Jan 1, 2020. Many other packages in the ecosystem have dropped 2.7 support at this point as well.

I would be in favor of a similar approach here, dropping Python 2.7 support from master going forward. If we need/want to make a bug fix release for 0.11.x that maintains 2.7 support we can always create a branch for that.

Dropping 2.7 from our CI would also avoid needing to fix some recent failures on Windows due to lack of conda packages as seen in #269.

**Comment by xnox** [comment]
python2 pyfftw dropped from ubuntu & debian.

**Comment by hgomersall** [comment]
Seems reasonable. Python itself is EOL from 2020 right? We can create a legacy branch and then carry on changes without worrying about python 2.7. Do you think we should explicitly remove 2.7 support? I think there is very little that is uncommon at the moment, but I can see the benefit of allowing some of the python 3 changes (which are starting to get quite significant!).
