### ISSUE TITLE
Question: Memory usage of the output array of builder.rfftn and builder.irfftn

### ISSUE THREAD

**Issue by nonmean** [pyFFTW/pyFFTW#275]
Dear pyFFTWer,

right now I am trying to optimize my code with a heavy calculation of builders.rfftn and builders.irfftn with zero-padding. My question is:

a new output array will be created during every call of rfftn and irfftn？ If this is true, I need to switch to FFTW object and keep the output array by myself to prevent the cost of create new array.

or the output array is kept by cython during the life time of the calculation？

Thank you so much for your help!

**Comment by hgomersall** [comment]
builders returns an FFTW object, and is simply intended as a way to easily construct the FFTW object. If you want to use a very simplified approach, use interfaces.

Stackoverflow is the preferred way to ask questions about pyfftw - I get notified about the questions and far more people will be able to answer you. Closing now as its not an issue.
