### ISSUE TITLE
making a new release

### ISSUE THREAD

**Issue by grlee77** [pyFFTW/pyFFTW#280]
It looks like we should make a new release now that SciPy 1.4 is officially out (see #279).

Of the open PRs I think we should merge #278 prior to tagging the release. Is there anything else others want to see merged beforehand?

**Comment by grlee77** [comment]
pyFFTW/pyFFTW-wheels#29 is now successfully building wheels for Python 3.8 aside from Windows where the failures look like they are just the dask-related ones fixed by #278.

**Comment by mnhauke** [comment]
I'm the maintainer of the openSUSE package.
pyFFTW 0.11.1 fails to build on openSUSE Tumbleweed (rolling release) since some time because of the issues with SciPy 1.4 and the packages was recently tagged to be dropped soon if there are no fixes.
Do you have an ETA for the new release ?
Thanks.

**Comment by hgomersall** [comment]
I think we can probably do it... @grlee77 ?

**Comment by grlee77** [comment]
I am away at a conference through Wednesday, but can work on it Thurs/Fri. I don't think there is much left to do.

**Comment by grlee77** [comment]
@mnhauke:
If you are willing to apply a patch to the current release (not sure on openSUSE policy regarding this), I think just the following patch corresponding to #265 should fix the issue.

https://patch-diff.githubusercontent.com/raw/pyFFTW/pyFFTW/pull/265.patch

**Comment by mnhauke** [comment]
@grlee77  https://github.com/pyFFTW/pyFFTW/pull/265 fixes the issue. Thanks.
https://build.opensuse.org/package/show/openSUSE:Factory/python-pyFFTW builds fine again :+1:

**Comment by grlee77** [comment]
v0.12.0 has now been released on PyPI and conda-forge
