### ISSUE TITLE
SciPy 1.4.x compatibility (new FFT module)

### ISSUE THREAD

**Issue by dperdios** [pyFFTW/pyFFTW#282]
Few days ago, SciPy 1.4.0 has been released with updates to the `fft` module (see [release note](https://github.com/scipy/scipy/releases/tag/v1.4.0)).

This results in an `ImportError: cannot import name '_fftpack' from 'scipy.fftpack'` when importing `pyfftw`.

This error has been produced using `python-3.7.5`, `scipy-1.4.1`,  `numpy-1.18.0`, and `pyfftw-0.11.1`.

**Comment by dperdios** [comment]
Sorry did not see it was already open in another [issue](https://github.com/pyFFTW/pyFFTW/issues/279)...Closing it :)

**Comment by grlee77** [comment]
No problem, thanks for reporting
