### ISSUE TITLE
Import error with scipy.fftpack - Scipy 1.4.1

### ISSUE THREAD

**Issue by CompiledAtBirth** [pyFFTW/pyFFTW#284]
Hello,

- There seems to be an import error with scipy 1.4.1 related to scipy.fftpack.

`File "/home/user/.local/lib/python3.7/site-packages/pyfftw/__init__.py", line 43, in <module>
    from . import interfaces
  File "/home/user/.local/lib/python3.7/site-packages/pyfftw/interfaces/__init__.py", line 237, in <module>
    from . import scipy_fftpack
  File "/home/user/.local/lib/python3.7/site-packages/pyfftw/interfaces/scipy_fftpack.py", line 65, in <module>
    from scipy.fftpack import (dct, idct, dst, idst, diff, tilbert, itilbert,
ImportError: cannot import name '_fftpack' from 'scipy.fftpack' (/home/chartier/.local/lib/python3.7/site-packages/scipy/fftpack/__init__.py)
`

-  Everything worked again just by downgrading scipy (1.2.2 confirmed to work)

'pip3 install --user scipy==1.2.2'

Best

**Comment by hgomersall** [comment]
Please see #279
