### ISSUE TITLE
Unable to install pyfftw3 package

### ISSUE THREAD

**Issue by mshane87** [pyFFTW/pyFFTW#290]
While installing the package from command line, it is giving syntax error in line 81 of setup.py. Please help.
![image](https://user-images.githubusercontent.com/34945617/80593659-354c7f80-8a3f-11ea-9edf-519c0559e262.png)

**Comment by hgomersall** [comment]
That's pyfftw3 which is nothing to do with pyfftw. I think pyfftw3 is a dead project.
