### ISSUE TITLE
r2r plan

### ISSUE THREAD

**Issue by AlbertZhangHIT** [pyFFTW/pyFFTW#293]
Hi all, 

This is a question somehow off the topic of this project. 

I notice that in `pyFFTW` the fftw plan is created in `r2c/c2r` or the `rfft` which returns dimension-reduced results. But I'm more insterested in the feature `r2r`(DCT/DST) in the FFTW3 library. Do you have any plan for this feature?

I took a first try drafting a simple module to do this. The `fftw_plan_r2r_2d` was called in the snippet below but I got the NULL pointer message, which means the function `fftw_plan_r2r_2d` fails to creat a plan. I have no idea why it fails. The arrays `cf, cg` has been checked.

	for(j=0; j<n2; j++){
		for(i=0; i<n1; i++){
			cf[j*n1+i] = (*(npy_float64*)( f->data + i*(f->strides[0]) + j*(f->strides[1]) ));
			cg[j*n1+i] = (*(npy_float64*)( g->data + i*(g->strides[0]) + j*(g->strides[1]) ));
		}
	}

	fftw_plan planIn = fftw_plan_r2r_2d(n2, n1, cf, cg, FFTW_REDFT10, FFTW_REDFT10, FFTW_MEASURE);
	if(planIn == NULL){
		printf("fail to call fftw_plan \n");
	}

Thank you.
Best

**Comment by hgomersall** [comment]
This is mostly done in #256 but needs a little bit of tidying to complete the job. Please feel free to help with that, I'm sure it would be appreciated!

**Comment by AlbertZhangHIT** [comment]
My pleasure.

**Comment by hgomersall** [comment]
@AlbertZhangHIT I suggest moving discussion of this to that PR. We can help with any questions you have.
