### ISSUE TITLE
The new scipy interface `rfft` is not documented!

### ISSUE THREAD

**Issue by hgomersall** [pyFFTW/pyFFTW#299]
The new scipy interface is not included in the docs, even though it _does_ exist!

**Comment by hgomersall** [comment]
I've just realised, it is in the code base, it's just not on Read The Docs. Is there a problem with it updating?

**Comment by hgomersall** [comment]
The webhooks were missing on RTD. Now added, so hopefully this is fixed. I've done a manual rebuild of the docs in the mean time.

**Comment by chrisvalx** [comment]
the `scipy_fft` interface real FFTs seem to be included in the docs now as you mention above; I think you can close this issue

**Comment by hgomersall** [comment]
Thanks!
