### ISSUE TITLE
pyFFTW install on ppc64 (IBM power9) architecture

### ISSUE THREAD

**Issue by abonatto** [pyFFTW/pyFFTW#300]
Dear developers,

We recently got access to the new Bede GPU HPC system (https://n8cir.org.uk/supporting-research/facilities/nice/hardware/), built upon IBM Power9 processors and Nvidia V100 GPUs, in which we intend to install and use FBPIC (https://fbpic.github.io) to perform particle-in-cell simulations. pyFFTW is required to run FBPIC, and we usually install it by using conda / conda-forge ("conda install -c conda-forge pyfftw"). However, when trying to install it on Bede, we realized that there is no distribution available for the ppc64 architecture. For this reason, I am writing you to ask if there is any way to have pyFFTW installed on such architecture (my apologies if the question is too basic: this is my first contact with a non-x86 system).

Kind Regards,

Alex

**Comment by hgomersall** [comment]
There is very little to do to actually get it working on alternative architectures. Essentially you need to modify https://github.com/pyFFTW/pyFFTW/blob/master/include/cpu.h to provide the correct `simd_alignment` function for the architecture, then make the build script work for your arch. My understanding is FFTW should work just fine, though I've no idea how optimised it is for PPC. If the SIMD stuff is not enabled, the default `simd_alignment` (i.e. unaligned) might just work, in which case it would just be tweaking the build script.

If you're running Linux, once you have FFTW installed, installing pyFFTW is easy.

**Comment by abonatto** [comment]
Dear @hgomersall,

Thank you very much for your fast reply. Bede is running Red Hat Enterprise Linux 7, and FFTW 3.3.8 is available as a module to be loaded. I will try to implement the solution you suggested.

Regards,

Alex

**Comment by hgomersall** [comment]
No problem. Let us know what you manage, and if you feel inclined to push any changes to support PPC then we'd be happy to accept them.

**Comment by abonatto** [comment]
Dear @hgomersall,

Before trying to implement your suggestion, I decided trying to install pyfftw by using pip, after loading the FFTW module. Indeed, after loading the following modules on Bede,

```
module load cuda/10.2.89 gcc/8.4.0 openmpi/4.0.5 fftw/3.3.8
```

I tried to install pyfftw by using pip (`pip install pyfftw --user`), and I had the following error,
```
...
Build pyFFTW with support for FFTW with
  double precision + openMP
  single precision + openMP
  long precision + openMP
  building 'pyfftw.pyfftw' extension
  error: unknown file type '.pyx' (from 'pyfftw/pyfftw.pyx')
...
```
After a quick search, I found that it could be solved by installing cython, which I did (`pip install cython --user`) and managed to have pyfftw successfully installed. However, when I try to use it in python (`import pyfftw`), I get the following error,

```
>>> import pyfftw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/.../.local/lib/python3.8/site-packages/pyfftw/__init__.py", line 18, in <module>
    from .pyfftw import (
ImportError: /users/abonatto/.local/lib/python3.8/site-packages/pyfftw/pyfftw.cpython-38-powerpc64le-linux-gnu.so: undefined symbol: omp_get_thread_num
```
which seems to be related to OpenMP. By executing the following command, `
echo |cpp -fopenmp -dM |grep -i open`, taken from [here](https://stackoverflow.com/questions/1304363/how-to-check-the-version-of-openmp-on-linux), I verified my openMP version is 201511, i.e., 4.5.

Do you know if there is any compatibility issue between the current version of pyfftw and openMP 4.5?

Regards,

Alex

**Comment by hgomersall** [comment]
I have very little experience with OMP. It could be a version issue, but more likely it's a a simple path issue. If that's the issue, you can try updating the rpath on the library, with something like `patchelf --set-rpath '/path/to/omp' /users/abonatto/.local/lib/python3.8/site-packages/pyfftw/pyfftw.cpython-38-powerpc64le-linux-gnu.so` (you might need to check that).

Easiest might be to try using posix threads, which is supported by setting the environment variable `PYFFTW_USE_PTHREADS` before the build.

**Comment by abonatto** [comment]
Dear @hgomersall,

After defining the environment variable (`PYFFTW_USE_PTHREADS = True`) and forcing pip to recompile pyfftw from source,
```
pip install --user --force-reinstall --ignore-installed --no-binary :all: pyfftw
```
I managed to have pyfftw working.

Again, thank you very much for your help!

Alex
