### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by hgomersall** [pyFFTW/pyFFTW#301]
It's not currently implemented.

**Comment by hgomersall** [comment]
How are Mac binaries defined? Also, anyone know about the M1?

**Comment by HaHeho** [comment]
(I believe) I am using `fftw 3.3.9` from brew with `pyfftw 0.12.0` from conda-forge successfully in `Python 3.9.1` .

Not implemented in what sense?

**Comment by hgomersall** [comment]
In the sense it isn't in PyPI or in any of the test matrices.

**Comment by akx** [comment]
Is https://github.com/pyFFTW/pyFFTW-wheels the project currently used to build wheels for PyPI too? 

(I'm trying to build pyFFTW on macOS on Python 3.9 against a Homebrew FFTW to not much success ("Could not find any of the FFTW libraries"), so a wheel would be nice...)

**Comment by hgomersall** [comment]
@grlee77 python 3.8 uses a scipy wheel build on a rackspace server. I vaguely remember something about this, but not the details. I think you implemented this bit...?

Just implementing the test matrix changes now...

**Comment by grlee77** [comment]
I will have to go back and see what was complete here. We can potentially have multibuild upload the wheels to https://anaconda.org/multibuild-wheels-staging/, which is what I had done recently a couple of other places.

2-3 months ago Travis started limiting jobs to 10,000 free credits per month for open source projects. On linux, 1 minute = 10 credits, but I think OS X was 5 times more expensive. Given that we only have linux jobs on Travis and are not super active with new PRs, maybe 1000 minutes / month will be okay. If so we can probably keep things mostly as is just changing from travis-ci.org to travis-ci.com. For larger projects like SciPy and scikit-image these free credits get exhausted within a day or two, so they had to move away from using Travis.

Another alternative to [multibuild](https://github.com/matthew-brett/multibuild) is to use [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) with GitHub Actions and the wheels will show up directly in the Actions tab in this repository. I have not done this myself, but matplotlib and scikit-image are now using this approach: https://github.com/scikit-image/scikit-image/pull/5080

It is also possible to add aarch64 support via cibuildwhel on linux: https://github.com/scikit-image/scikit-image/pull/5197

**Comment by grlee77** [comment]
I can update #285 to also drop testing on Python 3.6 and we can support only 3.7, 3.8 and 3.9 for an upcoming release?

Also, the Travis credits mentioned above are per organization, not repository so pyFFTW and pyFFTW-wheels would share credits. 

If we go the `cibuildwheel` route all wheels would be built within the main repository and pyFFTW-wheels could be deactivated. Not sure how much time that would take to set up, though.

**Comment by hgomersall** [comment]
Dropping 3.6 seems reasonable. Would you mind adding 3.9 at the same time? I was going to do that but hit the issues with the scipy wheels.

**Comment by akx** [comment]
3.6 is still a supported version, I wouldn't drop that.

Also, if it helps, you could migrate from Travis to GitHub Actions which is fully free for open source projects, and I have this tool that helps with migrating... https://akx.github.io/travis-to-github-actions/

**Comment by grlee77** [comment]
> 3.6 is still a supported version, I wouldn't drop that.

The latest releases of NumPy and SciPy have dropped 3.6 and only provide wheels for 3.7-3.9 on PyPI, so I don't think it makes sense for us to continue to support it here longer than those upstream projects. conda-forge also dropped 3.6 build quite a while ago. 

In practice it will continue to work on 3.6 for users who build from source.

> GitHub Actions is fully free for open source projects, and I have this tool that helps with migrating... https://akx.github.io/travis-to-github-actions/

Thanks, I was not aware of this utility. Our Travis script here is not too complicated so it is probably fairly straightforward to switch it over.

**Comment by grlee77** [comment]
The support policy NumPy is recommending to the community is here:
https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule

**Comment by akx** [comment]
Okay, fair enough – I wasn't aware NumPy and SciPy had this policy. Good for them really 😄

**Comment by garrettwrong** [comment]
Hi, I just wanted to report that I am also having some trouble installing pyfftw only against a clean 3.9 python (3.6, 3.7, 3.8 have been okay) on linux.  I appear to get the wheels for those versions, but pip attempts install from source for 3.9 because the wheel is n/a.

Superficially, it appears cython is needed (as stated in your docs), but is not required to be installed by the package.  While I can probably work around this in my package, I'm hesitant to fix other packages packaging in my package. Probably it would be better to do something here. I see discussion of the wheels above, but no mention of fixing the packaging.  Is anyone working on that already? Can I help?

**Comment by hgomersall** [comment]
@garrettwrong there have been various debates about making cython a dependency. It was long enough ago that I can't remember either the start point, the conclusion, nor my position! The argument is something like if you're building from scratch you don't need to make your build tools a dependency (much like gcc or msvc aren't "dependencies").

**Comment by akx** [comment]
@hgomersall Wouldn't that be a [`setup_requires`](https://pip.pypa.io/en/stable/reference/pip_install/#controlling-setup-requires) thing?

**Comment by grlee77** [comment]
If I recall correctly we used to ship the generated source files so that Cython was not a dependency, but this also has issues where source files generated with an older Cython may not work with new Python versions, etc. In general I think it is best to not ship the compiled files.

I could update #226 which adds a `pyproject.toml` (which includes Cython in the requirements). I think that would resolve the issue

**Comment by garrettwrong** [comment]
Yes I think both `setup_requires` and `pyproject.toml` would be able to solve this problem for people/projects that are missing Cython during pip installs.  I think the later is becoming more common. Thanks for considering.

**Comment by f-brinkmann** [comment]
Is this fixed by now? I wasn't sure from going through the tread. I have a project where pyfftw still fails for Python 3.9. Apparently because it's trying to build the wheel without success. You can find the Travis output here in case it is interesting to see: https://travis-ci.org/github/pyfar/pyfar/builds/773783560

**Comment by garrettwrong** [comment]
@f-brinkmann , I have been following.. I have a project in similar situation. I think a workable patch has been merged, but no new releases cut (either a 3.9 wheel or a new PyFFTW release).

**Comment by garrettwrong** [comment]
@grlee77 , is there an ETA for a py39 wheel or next release (0.12.1) that would include `pyproject.toml` patch? Thanks!

**Comment by grlee77** [comment]
Hi @garrettwrong, I do want to make a 0.13 release that includes the recent real-to-real transform work, but didn't have a specific time frame in mind. I would agree that we are overdue for a release, though. Let me first see if our existing pyFFTW-wheels repo is still close to a working state for building wheels or if significant refactoring will be needed. 

If I recall correctly, there was interest previously from @hgomersall in trying to make the release process more automated here. We did work recently at scikit-image on enabling automatically building and uploading wheels to PyPI via GitHub Actions upon pushing a tag to the repo, but it would require a decent bit of effort to adapt that approach here.

**Comment by f-brinkmann** [comment]
@grlee77, is there any news on the 0.13 release. We are starting to thing about making pyfftw an optional dependency in our package. But this would make testing and usage more complicated and we'd like to avoid that.

**Comment by f-brinkmann** [comment]
@grlee77 , thanks for the quick update. We'll discuss the option of using the newer SciPy version.

I think someone mentioned that travis might be open to extend free usage limits for non-profit open software. Maybe it's worth asking depending on how much work moving to cibuildwheel is.

**Comment by st-walker** [comment]
Is there anything anyone can do to help this along?  This is for Python 3.9 but Python 3.10 has just been released.  I don't wish to downplay the amount of work involved, especially as you're of course volunteers, but it's now two versions behind.  So I'm just wondering what is involved and what makes it so challenging.  Many thanks.

**Comment by hgomersall** [comment]
Currently the wheels build is not working. @grlee77 created that, so I'm a bit out of the loop, though I'm happy to help any way I can to get it out.

**Comment by JeppeKlitgaard** [comment]
@hgomersall @grlee77 

This can be closed once a release has been made. Release mechanism should be the same as before with wheels automatically being uploaded to pypi through the GitHub Actions workflow (though this is untested)

**Comment by grlee77** [comment]
v0.13.0 is up on PyPI and supports Python 3.9 and 3.10
