### ISSUE TITLE
Tag v0.12.0 is not an ancestor of master

### ISSUE THREAD

**Issue by jwoillez** [pyFFTW/pyFFTW#312]
Just a note to let you know that the current master branch does not have the v0.12.0 tag as an ancestor. `git describe` still gives `v0.11.1-66-gd74d032` rather than something derived from the current released `v0.12.0` version. This keeps the version of pyFFTW installed from master as based on `v0.11.1`.

**Comment by grlee77** [comment]
Yeah, I must have messed this up when doing the 0.12.0 release. Not sure what we can do about it now, though? If we do a new release candidate soon, we need to make sure to use 0.13.0rc0!

**Comment by grlee77** [comment]
The v0.13.0 tag should be an ancestor of master, so versions on new commits should now show up as something like `0.13.0+1.ge6e475c` (i.e. no longer erroneously starting from 0.11)
