### ISSUE TITLE
Failure to find FFTW libraries on Mac Big Sur (11.3.1)

### ISSUE THREAD

**Issue by gabrielb09** [pyFFTW/pyFFTW#314]
Im sure anyone reading this is all too familiar with issues such as mine (given by the number of posts referring to this issue). I am running Mac OS X Big Sur (11.3.1). I have python 3.9.4 installed via pyenv which is installed through home-brew. I have also installed FFTW through home-brew and followed the Mac installation instructions. 

`export DYLD_LIBRARY_PATH=/usr/local/lib`
`export LDFLAGS="-L/usr/local/include"  `
`export CFLAGS="-I/usr/local/include"  `

Unfortunately pyfftw still fails to find the FFTW libraries when installing via pip. Any advice would be greatly appreciated.

**Comment by andrej5elin** [comment]
I had the same issue. Please try these instructions:

https://github.com/andrej5elin/howto_fftw_apple_silicon

**Comment by gabrielb09** [comment]
Ah, perhaps it is worth me clarifying, I am not running Apple Silicon, still on Intel. Are these instructions valid for intel x86 architecture?

**Comment by andrej5elin** [comment]
Well, the fftw compilation step is M1-specific, but the pyfftw install should work. Also see the workaround of https://github.com/pyFFTW/pyFFTW/issues/303#issue-797681591 

If you plan to compile fftw yourself on Intel Macs replace the --enable-neon --enable-armv8-cntvct-el0 with --enable-avx2 or one of the other SIMD options that fftw allows to use and you should be fine.

**Comment by gabrielb09** [comment]
It all makes sense now, thank you for bearing with me!

**Comment by volkov-maxim** [comment]
For MacBook Air @ M1 a mix of instructions helped me:
1. `brew install fftw`
2. Find locations of `libfftw3.dylib` and `fftw3.h` and [set environmental variables](https://github.com/pyFFTW/pyFFTW?tab=readme-ov-file#mac-osx)

   Example: 
```
export DYLD_LIBRARY_PATH=/opt/homebrew/lib
export LDFLAGS="-L/opt/homebrew/include"
export CFLAGS="-I/usr/local/include"
```
3. Clone `pyFFTW` repo 

   `git clone git@github.com:pyFFTW/pyFFTW.git`

4. Install `pyFFTW` 
   
   `CFLAGS="-Wno-implicit-function-declaration" pip install -e . -v`

Links:
- https://github.com/pyFFTW/pyFFTW?tab=readme-ov-file#mac-osx
- https://github.com/andrej5elin/howto_fftw_apple_silicon
