### ISSUE TITLE
How to install pyFFTW in Mac M1?

### ISSUE THREAD

**Issue by MR-T77** [pyFFTW/pyFFTW#316]
I'm installing a conda environment (with miniforge) in a MacOs M1 with tensorflow and other libraries that require pyFFTW, but I can't install pyFFTW. Any workaround?

> pip install pyfftw
Collecting pyfftw
  Using cached pyFFTW-0.12.0.tar.gz (137 kB)
Requirement already satisfied: numpy<2.0,>=1.10 in /Users/asapinto/miniforge3/envs/last/lib/python3.8/site-packages (from pyfftw) (1.21.2)
Building wheels for collected packages: pyfftw
  Building wheel for pyfftw (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/asapinto/miniforge3/envs/last/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0k/hz9yngm56nz1htdc3c3t3d0c0000gn/T/pip-install-t9_j9w8n/pyfftw/setup.py'"'"'; __file__='"'"'/private/var/folders/0k/hz9yngm56nz1htdc3c3t3d0c0000gn/T/pip-install-t9_j9w8n/pyfftw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/0k/hz9yngm56nz1htdc3c3t3d0c0000gn/T/pip-wheel-ls9ariz0
       cwd: /private/var/folders/0k/hz9yngm56nz1htdc3c3t3d0c0000gn/T/pip-install-t9_j9w8n/pyfftw/
  Complete output (25 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11.0-arm64-3.8
  creating build/lib.macosx-11.0-arm64-3.8/pyfftw
  copying pyfftw/config.py -> build/lib.macosx-11.0-arm64-3.8/pyfftw
  copying pyfftw/_version.py -> build/lib.macosx-11.0-arm64-3.8/pyfftw
  copying pyfftw/__init__.py -> build/lib.macosx-11.0-arm64-3.8/pyfftw
  creating build/lib.macosx-11.0-arm64-3.8/pyfftw/builders
  copying pyfftw/builders/builders.py -> build/lib.macosx-11.0-arm64-3.8/pyfftw/builders
  copying pyfftw/builders/__init__.py -> build/lib.macosx-11.0-arm64-3.8/pyfftw/builders
  copying pyfftw/builders/_utils.py -> build/lib.macosx-11.0-arm64-3.8/pyfftw/builders
  creating build/lib.macosx-11.0-arm64-3.8/pyfftw/interfaces
  copying pyfftw/interfaces/cache.py -> build/lib.macosx-11.0-arm64-3.8/pyfftw/interfaces
  copying pyfftw/interfaces/__init__.py -> build/lib.macosx-11.0-arm64-3.8/pyfftw/interfaces
  copying pyfftw/interfaces/scipy_fft.py -> build/lib.macosx-11.0-arm64-3.8/pyfftw/interfaces
  copying pyfftw/interfaces/dask_fft.py -> build/lib.macosx-11.0-arm64-3.8/pyfftw/interfaces
  copying pyfftw/interfaces/numpy_fft.py -> build/lib.macosx-11.0-arm64-3.8/pyfftw/interfaces
  copying pyfftw/interfaces/scipy_fftpack.py -> build/lib.macosx-11.0-arm64-3.8/pyfftw/interfaces
  copying pyfftw/interfaces/_utils.py -> build/lib.macosx-11.0-arm64-3.8/pyfftw/interfaces
  UPDATING build/lib.macosx-11.0-arm64-3.8/pyfftw/_version.py
  set build/lib.macosx-11.0-arm64-3.8/pyfftw/_version.py to '0.12.0'
  running build_ext
  error: Could not find the FFTW header 'fftw3.h'
  ----------------------------------------
  ERROR: Failed building wheel for pyfftw
  Running setup.py clean for pyfftw
Failed to build pyfftw
Installing collected packages: pyfftw
    Running setup.py install for pyfftw ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/asapinto/miniforge3/envs/last/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0k/hz9yngm56nz1htdc3c3t3d0c0000gn/T/pip-install-t9_j9w8n/pyfftw/setup.py'"'"'; __file__='"'"'/private/var/folders/0k/hz9yngm56nz1htdc3c3t3d0c0000gn/T/pip-install-t9_j9w8n/pyfftw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/0k/hz9yngm56nz1htdc3c3t3d0c0000gn/T/pip-record-blpjiwwp/install-record.txt --single-version-externally-managed --compile --install-headers /Users/asapinto/miniforge3/envs/last/include/python3.8/pyfftw
         cwd: /private/var/folders/0k/hz9yngm56nz1htdc3c3t3d0c0000gn/T/pip-install-t9_j9w8n/pyfftw/
    Complete output (7 lines):
    running install
    running build
    running build_py
    UPDATING build/lib.macosx-11.0-arm64-3.8/pyfftw/_version.py
    set build/lib.macosx-11.0-arm64-3.8/pyfftw/_version.py to '0.12.0'
    running build_ext
    error: Could not find the FFTW header 'fftw3.h'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/asapinto/miniforge3/envs/last/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0k/hz9yngm56nz1htdc3c3t3d0c0000gn/T/pip-install-t9_j9w8n/pyfftw/setup.py'"'"'; __file__='"'"'/private/var/folders/0k/hz9yngm56nz1htdc3c3t3d0c0000gn/T/pip-install-t9_j9w8n/pyfftw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/0k/hz9yngm56nz1htdc3c3t3d0c0000gn/T/pip-record-blpjiwwp/install-record.txt --single-version-externally-managed --compile --install-headers /Users/asapinto/miniforge3/envs/last/include/python3.8/pyfftw Check the logs for full command output.

**Comment by asross** [comment]
I'm having the same problem :(

**Comment by MR-T77** [comment]
@asross yes, a while after this, it started being available in conda-forge, but I forgot to close it.

**Comment by Mark2000** [comment]
Is there any plan to make arm64 builds for Mac available through PyPI?

**Comment by hgomersall** [comment]
It's certainly something that is valuable though I lack the hardware and the time to make it happen. I'm happy to take pull requests and contributions to this end, so please do feel free to make it happen. I don't think it should be too hard and I'm happy to help.

**Comment by Mark2000** [comment]
I’ve never worked with PyPI or building wheels before so entirely unfamiliar with the process. If you could offer some advice on where to start, I’ll carve out some time and see how far I can get.

**Comment by asapsmc** [comment]
I'm also completely unexperienced on this (PyPI), but I'm willing to contribute to this.

**Comment by hgomersall** [comment]
It's probably mostly in `pypojects.toml`. I'll be honest though that I haven't really had much to do with that either. It was done by @grlee77 with most of the recent work done by @JeppeKlitgaard .

**Comment by JeppeKlitgaard** [comment]
Building for ARM Macs requires cross-compilation as we don't have access to ARM Macs on the CI – Apple doesn't provide a lot of nice tooling for this as far as I am aware. Walled garden and all that.

The situation may change later this year (See: https://github.com/github/roadmap/issues/528). I don't use Mac and don't have access to the hardware, but using the build guide in the README users may be able to build the wheel locally on their M1/M2 Macs, but that is a task for adventurous end-users. Once Apple or GitHub provide runners with ARM Mac's, we can build and publish wheels for these systems.

**Comment by matteobachetti** [comment]
@JeppeKlitgaard M1 Macs are a thing on Github Action now! https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
