### ISSUE TITLE
Real-to-real transformations seem to be excluded from the latest release

### ISSUE THREAD

**Issue by lukastk** [pyFFTW/pyFFTW#317]
In the API documentation for [pyfftw.builders](https://pyfftw.readthedocs.io/en/latest/source/pyfftw/builders/builders.html) version 0.12.0 the functions

- `pyfftw.builders.dct`
- `pyfftw.builders.dst`

are listed, but do not seem to be included in the latest pip release of pyfftw. Inspecting `pyfftw/builders/builders.py`in site-packages, these functions do seem to be missing (although they are present in the repository).

If I run the following snippet,

```python
d = pyfftw.empty_aligned(128, dtype='float64')
e = pyfftw.empty_aligned(128, dtype='float64')

dct_transform = pyfftw.FFTW(d, e, direction='FFTW_REDFT00')
```

taken from the [tutorial](https://pyfftw.readthedocs.io/en/latest/source/tutorial.html#one-dimensional-transforms) I get the error _Invalid direction: The direction is not valid for the scheme. Try setting it explicitly if it is not already_.

It seems that all the cosine and sine transformations are excluded from the latest public version of pyfftw. Apologies if I'm pointing out the obvious here. If nothing else I just wanted to point out the discrepancy between the documentation and the released version.

**Comment by hgomersall** [comment]
Yeah, the release is old and needs to be updated soon...

**Comment by grlee77** [comment]
A new release (0.13.0) has been published that has these functions
