### ISSUE TITLE
pyFFTW evaluation 

### ISSUE THREAD

**Issue by emthompson-usgs** [pyFFTW/pyFFTW#321]
Hi, I'm struggling to achieve the improved evaluation times offered by pyFFTW. I've tried a few approaches, installing from source, with pip, and with conda. And for each, I'm not able to see the improved speed described in the tutorial. Specifically, I've been running the example code given [here](https://pyfftw.readthedocs.io/en/latest/source/tutorial.html#integration-with-3rd-party-libraries). 

To keep things simple, I'll describe the steps I've done most recently with conda. First, I create  and activate a virtual environment
```
conda create -n fftw -y ipython numpy scipy pyfftw
conda activate fftw
```
Then, in ipython, I run the test code:
```
import pyfftw
import multiprocessing
import scipy.signal
import scipy.fft
import numpy
from timeit import Timer

a = pyfftw.empty_aligned((128, 64), dtype='complex128')
b = pyfftw.empty_aligned((128, 64), dtype='complex128')

a[:] = numpy.random.randn(128, 64) + 1j*numpy.random.randn(128, 64)
b[:] = numpy.random.randn(128, 64) + 1j*numpy.random.randn(128, 64)

t = Timer(lambda: scipy.signal.fftconvolve(a, b))

print('Time with scipy.fft default backend: %1.3f seconds' %
      t.timeit(number=100))

# Configure PyFFTW to use all cores (the default is single-threaded)
pyfftw.config.NUM_THREADS = multiprocessing.cpu_count()

# Use the backend pyfftw.interfaces.scipy_fft
with scipy.fft.set_backend(pyfftw.interfaces.scipy_fft):
     # Turn on the cache for optimum performance
     pyfftw.interfaces.cache.enable()

      # We cheat a bit by doing the planning first
     scipy.signal.fftconvolve(a, b)

     print('Time with pyfftw backend installed: %1.3f seconds' %
            t.timeit(number=100))
```
Which yields the following output: 
```
Time with scipy.fft default backend: 0.108 seconds
Time with pyfftw backend installed: 0.145 seconds
```
So clearly my install is not performing up to expectations. Any guidance on how I can improve things would be greatly appreciated.

**Comment by HaHeho** [comment]
You should incorporate the "planner" and it's effort configuration, as for example shown here https://github.com/pyFFTW/pyFFTW/issues/310#issuecomment-946342809. The discussion around it should also explain under which circumstances you may expect a speedup with FFTW.

**Comment by emthompson-usgs** [comment]
So what you are saying is that example is not fully self contained. In order to get the relative speedup that is presented in the tutorial, the code needs to be modified.

**Comment by hgomersall** [comment]
No, that code is self contained. The planning stage happens implicitly: `# We cheat a bit by doing the planning first`.

Scipy has got better and it might be that you just don't get a speed up anymore on those sizes of arrays. I suspect that there is intrinsic overhead in using Scipy that isn't necessarily optimised for out usage. I'd be interested to see if that persists for all array sizes.
