### ISSUE TITLE
Push new release to `pypi`

### ISSUE THREAD

**Issue by JeppeKlitgaard** [pyFFTW/pyFFTW#335]
It has been a while since a release has been pushed to `pypi` and wheels are missing for many common configurations.

Pushing a release should be easy now that #323 has been merged (I believe just pushing a tag? @grlee77).

When a release is pushed, the following issues can be closed:
- #335 
- #301
- #309
- #266 
- #317 
- #312 (by having latest tag be an ancestor)
- #252 (I think)
- #234 
- #144 

@hgomersall @grlee77

**Comment by grlee77** [comment]
Yeah, I think we should go ahead and try to get v0.13.0 out. @hgomersall, does this sound good to you? If so I can push a tag later today or tomorrow.

**Comment by hgomersall** [comment]
Let's do it!

**Comment by grlee77** [comment]
please review the release notes in #338

**Comment by grlee77** [comment]
I tagged a `v0.13.0rc0` release candidate and pushed here just now. The build is in process here: https://github.com/pyFFTW/pyFFTW/actions/runs/1616009234

Assuming that goes well we can merge the release notes PR and then tag a final release.

**Comment by grlee77** [comment]
All wheels built and the artifact was produced, and all wheels appear here: https://pypi.org/project/pyFFTW/0.13.0rc0/#files

however, there was a failure in upload of the source release: https://github.com/pyFFTW/pyFFTW/runs/4619310415?check_suite_focus=true#step:6:224
so it is not present. We can still add it by running `python setup.py sdist` locally and then uploading that.

The problem may just be a capitalization error (when I generate the file locally it is named `pyFFTW-0.13.0rc0.tar.gz` but the filename in the error message was all lowercase.

**Comment by JeppeKlitgaard** [comment]
The original code was probably taken from Appveyor where the filesystem is case-insensitive.

The offending line seems to be https://github.com/pyFFTW/pyFFTW/blob/d520a484fb0bea4ee7512fc17417d6b22ba13ddf/.github/workflows/wheel_tests_and_release.yml#L208.

**Comment by grlee77** [comment]
I tagged 0.13.0 and it has been published on PyPI. The new conda-forge builds are pending review: https://github.com/conda-forge/pyfftw-feedstock/pull/47
