### ISSUE TITLE
pyFFTW 0.13.0 - `pyfftw.interfaces.numpy_fft.ifftn` different results than `pyfftw.builders.ifftn`

### ISSUE THREAD

**Issue by cernyd** [pyFFTW/pyFFTW#342]
Hi, for the past couple of days, I've been unable to figure this out.

`pyfftw.interfaces.numpy_fft.fftn` has the same output as `pyfftw.builders.fftn`, **however** `pyfftw.interfaces.numpy_fft.ifftn` gives me completely different results than `pyfftw.builders.ifftn` with the same default settings. The `ifftn` from builders seems to perform the operations on only one axis despite the axes being set correctly. 

I checked the manual and found no indication `pyfftw.builders.ifftn` should work differently than the numpy "drop-in" version - is there something I'm missing?

Thanks in advance.

## Setup info
- Python 3.10.1 (main, Dec  6 2021, 22:25:40) [Clang 13.0.0 (clang-1300.0.29.3)]
- Numpy 1.21.4
- pyFFTW 0.13.0

**Comment by grlee77** [comment]
Can you post code that reproduces the problem? With v0.13 from PyPI on linux the following seems to be working okay.

```Python
import numpy as np

from pyfftw.interfaces import numpy_fft
from pyfftw import builders


# random input data
x = np.random.randn(64, 64)
x = x + 1j * np.random.randn(64, 64)

y1 = numpy_fft.ifftn(x)
IFFTN = builders.ifftn(x)
y2 = IFFTN(x)

np.testing.assert_allclose(y1, y2)
```

I did encounter a bug related to missing threading support in the conda-forge package, but that is a separate issue to investigate.

**Comment by cernyd** [comment]
@grlee77 I probably found the issue, numpy (i)fftn promotes `float32` to `complex128` but pyfftw does not promote - `float32` has result of `complex64`. I know this is written in the caveats section, I missed this because the output datatypes are the same when using `float64` as input, when i switched input data to `float32`, the outputs suddenly
gave completely different results.

Maybe this could be emphasized in the `pyfftw.builders` docs or `pyfftw.interfaces`, I know the caveats are listed but are
still easy to miss.

Sorry for the trouble!
