### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by robertdstein** [pyFFTW/pyFFTW#350]
It would be great if wheels/PyPI could be set up for the newly-released python 3.11, as well as python 3.7-3.10. I am not sure if this was already planned.

**Comment by hgomersall** [comment]
I agree. I think the source build should work...?

**Comment by paulmueller** [comment]
Python 3.11 wheels would be great!

pip install currently fails on Windows GH Actions with Python 3.11.

**Comment by hgomersall** [comment]
Keen to see pull requests on this. I think it's fair to say we're not able to give pyFFTW the maintenance it requires at the moment, so perhaps we need to think about more maintainers. @grlee77 thoughts?

**Comment by JeppeKlitgaard** [comment]
I am happy to take a look at this – I suspect this is just a matter of updating the wheel building workflow to include 3.11.

**Comment by hgomersall** [comment]
@JeppeKlitgaard might you be interested in taking on some of the release role?

**Comment by JeppeKlitgaard** [comment]
> @JeppeKlitgaard might you be interested in taking on some of the release role?

I would be happy to continue to help out with the CI builds and releases, though I am wary of adding another commitment for me to neglect and feel guilty about. I am plenty happy to be pinged about release and CI related issues, but I admittedly don't have a deep understanding of the way pyFFTW works.

**Comment by JeppeKlitgaard** [comment]
If #351 gets merged we should automagically get a bunch of new wheels that expands `pyFFTW` support. Most usefully this includes Python 3.11 across Windows, Linux, and Mac, but also features Windows 32-bit and Windows ARM 64-bit along with PyPy 3.8 wheels.
