### ISSUE TITLE
v0.13.1 release supporting python 3.11

### ISSUE THREAD

**Issue by hgomersall** [pyFFTW/pyFFTW#353]
I think we need this asap. @JeppeKlitgaard I'm a little out of touch with the release strategy - you suggested it's just a tag that's needed. Would you like to push that (since you did the necessary changes to make it possible)? I think we're still on 0.13.1 (no API changes).

**Comment by JeppeKlitgaard** [comment]
I am happy to push that, though I am not familiar with the way in which we've previously generated the changelogs: https://github.com/pyFFTW/pyFFTW/releases/tag/v0.13.0 suggests that perhaps a software aided in the formulation?

**Comment by JeppeKlitgaard** [comment]
I have pushed a tag `v0.13.1` and this should automatically make a release. We can then update the release to include notes

**Comment by JeppeKlitgaard** [comment]
From what I can gather @grlee77 uses this: https://github.com/scikit-image/scikit-image/blob/main/RELEASE.txt

It fairly involved considering and might be too much effort for the return it gives. GitHub has a fairly good release note generator which I have used to update the release notes. Alternatively we can try and set up a `towncrier` setup if you think this would be beneficial.

**Comment by hgomersall** [comment]
> From what I can gather @grlee77 uses this: https://github.com/scikit-image/scikit-image/blob/main/RELEASE.txt
> 
> It fairly involved considering and might be too much effort for the return it gives. GitHub has a fairly good release note generator which I have used to update the release notes. Alternatively we can try and set up a `towncrier` setup if you think this would be beneficial.

`towncrier`? I'm all for keeping it simple. I expect the github one is plenty good enough. One's knowledge gets stale quickly!

**Comment by hgomersall** [comment]
That looks good to me. Is that completed then?

**Comment by JeppeKlitgaard** [comment]
Yea, feel free to close this. I'll add details to the release notes now in that case
