### ISSUE TITLE
Feature request: Export fftw_version

### ISSUE THREAD

**Issue by phlibi** [pyFFTW/pyFFTW#355]
When pyFFTW is installed, it is fairly hard to tell the version of the underlying FFTW library matching their [release notes](https://fftw.org/release-notes.html). The version code in the shared library file name (e.g. libfftw3f.so.3.6.10 for FFTW 3.3.10) is *not* the release version, but follows the [Libtool versioning scheme](https://www.gnu.org/software/libtool/manual/html_node/Libtool-versioning.html). In request to this, Matteo Frigo told me that FFTW actually exports its version as `fftw_version` variable:

> printf("%s\n", fftw_version)  will tell you which version you are using.  See also fftw_cc for which compiler was used and which flags.

Feature request: Make `fftw_version` accessible in the Python module (and maybe also `fftw_cc`).

**Comment by mforbes** [comment]
This would be very nice.  I was having many performance related issues on ARM platforms, and would like to include some software checks to make sure that the appropriate version of the FFTW was being used.

**Comment by paugier** [comment]
A PR would of course be very welcome!
