### ISSUE TITLE
Undefined plan with nthreads

### ISSUE THREAD

**Issue by james-math** [pyFFTW/pyFFTW#358]
I just installed pyfftw from conda-forge and I'm getting an error when trying to create an FFTW object:

`import pyfftw`
`a = pyfftw.empty_aligned(128, dtype='complex128', n=16)`
`b = pyfftw.empty_aligned(128, dtype='complex128', n=16)`
`fft_object = pyfftw.FFTW(a, b)`

yields the error message:

`---------------------------------------------------------------------------`
`RuntimeError                              Traceback (most recent call last)`
`RuntimeError: Undefined plan with nthreads. This is a bug`
`Exception ignored in: 'pyfftw.pyfftw._fftw_plan_with_nthreads_null'`
`Traceback (most recent call last):`
`  File "/tmp/ipykernel_54559/4021097874.py", line 1, in <module>`
`RuntimeError: Undefined plan with nthreads. This is a bug`

**Comment by paugier** [comment]
This should be fixed by https://github.com/conda-forge/pyfftw-feedstock/pull/60
