### ISSUE TITLE
Moving pyfftw to the Meson build system

### ISSUE THREAD

**Issue by paugier** [pyFFTW/pyFFTW#368]
Scipy and scikit-learn moved to the Meson build system (see https://labs.quansight.org/blog/2021/07/moving-scipy-to-meson) and they seem to be very happy with this tool. meson-python is now mature.

In the long term, it could also be wise to use this good general purpose build system for pyfftw.

I worked on using Meson for the build of [Fluidsim](https://foss.heptapod.net/fluiddyn/fluidsim) and we like it. Since I need a robust pyfftw, I could work on modernizing pyfftw build system (removing setup.py and using Meson), but I'd like first to have the point of view of the maintainers.

**Comment by hgomersall** [comment]
I'm happy to see changes along these lines, particularly if it makes maintenance simpler. I'm very restricted on time currently and so have limited scope for making such changes, but if someone wants to grip the bull by the horns and improve the build experience I'd support the activity as best I can.

**Comment by hgomersall** [comment]
The build system is a bit of a mess at the moment, with various bits of legacy hanging around. Attempts have been made at various points to improve and modernise it by various people, but it's still a bit brittle. I think we do need to think about what other tools would work better.

**Comment by paugier** [comment]
pyfftw uses modern setuptools (supporing pep 517) which is perfectly fine for now. I'm closing since we do not need Meson.
