### ISSUE TITLE
Using the Cython interface in my own package ?

### ISSUE THREAD

**Issue by gabrielfougeron** [pyFFTW/pyFFTW#373]
Hi, 

I see that this package provides a Cython interface in `pyfftw.pxd`. As far as I can tell, this is not documented in the official documentation.
My question is: Is the interface stable enough for me to `cimport` it and use it in Cython ?

**Comment by hgomersall** [comment]
It hasn't changed in several years!

**Comment by hgomersall** [comment]
Are you proposing the just call the python functions through Cython? Are you not just effectively depending on the stability of the python API?

**Comment by gabrielfougeron** [comment]
In a nutshell, I'd like to call fftw in a nogil block.

**Comment by hgomersall** [comment]
I think that should work fine assuming Cython is happy. I would suggest limiting yourself to the normal calls.
