### ISSUE TITLE
Executing Pyfftw in a nogil block

### ISSUE THREAD

**Issue by gabrielfougeron** [pyFFTW/pyFFTW#374]
I think that should work fine assuming Cython is happy. I would suggest limiting yourself to the normal calls.

I think you can call `execute` with `nogil`. The innards of that are read-only properties so unless you're doing something nefarious to the class it should be ok. Is it more than just the execute part?

Have you noted that `execute` already runs as no-gil?

_Originally posted by @hgomersall in https://github.com/pyFFTW/pyFFTW/issues/373#issuecomment-1966291886_

**Comment by gabrielfougeron** [comment]
Sorry for the horrendous formatting of the previous message, this is straight from the "Reference in a new issue" feature from Github.

Anyway.

Coming back to the idea of computing ffts with the gil released, turns out you still need the gil to call `FTW.execute()`.
Here is the code to the execute method.

```cython
    cpdef execute(self):
        '''execute()

        Execute the planned operation, taking the correct kind of FFT of
        the input array (i.e. :attr:`FFTW.input_array`),
        and putting the result in the output array (i.e.
        :attr:`FFTW.output_array`).
        '''
        cdef void *input_pointer = (
                <void *>np.PyArray_DATA(self._input_array))
        cdef void *output_pointer = (
                <void *>np.PyArray_DATA(self._output_array))

        cdef void *plan = self._plan
        cdef fftw_generic_execute fftw_execute = self._fftw_execute
        with nogil:
            fftw_execute(plan, input_pointer, output_pointer)
```

In order to call it from a nogil block, this should really be marked nogil (and probably be cdef, I'm not sure)

HOWEVER, if `self._fftw_execute` and `self._plan` were not private, but readonly, I think I could get away with it.

My question is: how do you feel about those two properties being readonly ?

**Comment by hgomersall** [comment]
I think execute can happily be nogil for calling from Cython (though we should check that `np.PyArray_DATA` does not do anything pythony). Is this possible? This code is pretty ancient nowadays so things might have improved to make this sort of this possible/better now.

Do you have a reference to making it readonly? Does this just make it more broadly accessible from Cython?

**Comment by gabrielfougeron** [comment]
Hi Henry.I'm in vacations this week, but I'll try and submit a PR next week to show what I mean. Le 25 mars 2024 03:37, Henry Gomersall ***@***.***> a écrit :
I think execute can happily be nogil for calling from Cython (though we should check that np.PyArray_DATA does not do anything pythony). Is this possible? This code is pretty ancient nowadays so things might have improved to make this sort of this possible/better now.
Do you have a reference to making it readonly? Does this just make it more broadly accessible from Cython?
