### ISSUE TITLE
Wheels for macosx arm64

### ISSUE THREAD

**Issue by paugier** [pyFFTW/pyFFTW#382]
It would be good to build and upload on PyPI wheels for macosx arm64 (like numpy and scipy).

**Comment by hgomersall** [comment]
Since those targets are in the matrix, will a release work? Once you're happy with the current state, we can do a release. I think it just requires pushing a tag.

**Comment by paugier** [comment]
Unfortunately, macosx arm64 is not yet in the matrix!
