### ISSUE TITLE
setup: some targets should not require numpy to be installed

### ISSUE THREAD

**Issue by ghisvail** [pyFFTW/pyFFTW#46]
Targets like help or clean should not require numpy to be installed in order to execute. Again, this bug is to ease the packaging work where the clean command is usually executed before dependency resolution. 

The solution provided by scipy seems to be the widely accepted one, where the common metadata of the package are set first and the extension modules and package metadata are added if numpy is detected. Again, please have a look at my updated version of pyNFFT for a concrete example.

**Comment by hgomersall** [comment]
This should now be fixed in 208cb158c4e5cd0a2e2ee2be3ea55eb224220de3. Can you confirm this is satisfactory?

I heavily drew on your efforts in pyNFFT, so thanks for that.

**Comment by hgomersall** [comment]
Assuming fixed.
