### ISSUE TITLE
very slow test suite

### ISSUE THREAD

**Issue by ghisvail** [pyFFTW/pyFFTW#47]
The test suite is currently too slow to complete for the packaging build-bot in Debian / Ubuntu. A timeout is triggered and the build process is considered dead. At the moment, I am overriding the build process by asking it *NOT* to launch the test suite, which raised some eyebrows by the packaging reviewers. I am opening this bug to find a solution with you.

It is a respectable effort from you to provide a comprehensive test suite for your package and I don't want to ask you to downgrade your test suite so it can execute in a reasonable amount of time. That would just be silly.

Instead, I was thinking that you could provide different levels of testing, say for instance "quick" and "thorough", where the former executes only a restricted portion of the latter. I believe this is how big projects like numpy or scipy are doing it, but I could be mistaken.

Thoughts ?

**Comment by hgomersall** [comment]
Is this issue satisfied now?

**Comment by ghisvail** [comment]
Hi Henry, I have not checked this since. Will let you know.

**Comment by hgomersall** [comment]
No rush, just doing some issue maintenance.

**Comment by hgomersall** [comment]
I'm marking this as done. Please reopen if there is still a problem.
