### ISSUE TITLE
General problems with not being able to get things to work with Mac OS X

### ISSUE THREAD

**Issue by tantrev** [pyFFTW/pyFFTW#55]
Hello!

I have been trying to install this wonderful software but unfortunately receive this error when trying to compile it on my Mac:

"fatal error: 'fftw3.h' file not found"

In accordance with pyFFTW's homepage's recommendation, I have set my ~/.profile file to include the following settings:

export DYLD_LIBRARY_PATH=/opt/local/lib
export LDFLAGS="-L/opt/local/include"

It may be worth nothing that I installed FFTW-3 using Mac Ports and it yields the following output about the locations of its installed contents:

Port fftw-3 contains:
  /opt/local/bin/fftw-wisdom
  /opt/local/bin/fftw-wisdom-to-conf
  /opt/local/include/fftw3.f
  /opt/local/include/fftw3.f03
  /opt/local/include/fftw3.h
  /opt/local/include/fftw3l.f03
  /opt/local/include/fftw3q.f03
  /opt/local/lib/libfftw3.3.dylib
  /opt/local/lib/libfftw3.a
  /opt/local/lib/libfftw3.dylib
  /opt/local/lib/libfftw3_threads.3.dylib
  /opt/local/lib/libfftw3_threads.a
  /opt/local/lib/libfftw3_threads.dylib
  /opt/local/lib/pkgconfig/fftw3.pc
  /opt/local/share/info/fftw3.info
  /opt/local/share/info/fftw3.info-1
  /opt/local/share/info/fftw3.info-2
  /opt/local/share/man/man1/fftw-wisdom-to-conf.1.gz
  /opt/local/share/man/man1/fftw-wisdom.1.gz

Any ideas on what's going on by chance?  Thank you in advance.

**Comment by hgomersall** [comment]
Perhaps issue #52 is relevant here?

**Comment by hgomersall** [comment]
If you solve this for macports, and have a general patch to make it work more generally, that would be gratefully received.

**Comment by tantrev** [comment]
Issue #52 did the trick!  I just used binstar as the original bugposter recommended and that was able to work successfully.  I have a feeling the issue may somehow be related to the Anaconda python distribution I'm running but in any event, I'm happy it's working. :)

Cheers!  Thanks for the help.

**Comment by ketch** [comment]
I had the same problem (and I'm using Anaconda).  I got it to work finally by also setting CFLAGS:

    brew install fftw
    git clone git@github.com:hgomersall/pyFFTW.git
    cd pyFFTW
    export DYLD_LIBRARY_PATH=/usr/local/lib
    export LDFLAGS="-L/usr/local/include"
    export CFLAGS="-I/usr/local/include"
    pip install pyfftw

**Comment by hgomersall** [comment]
@ketch Thanks, I'll add that to the README.

**Comment by ketch** [comment]
Oops, some of the lines in my previous comment are unnecessary (irrelevant, in fact).  Here is a cleaner version:

    brew install fftw
    export DYLD_LIBRARY_PATH=/usr/local/lib
    export LDFLAGS="-L/usr/local/include"
    export CFLAGS="-I/usr/local/include"
    pip install pyfftw

**Comment by hgomersall** [comment]
It's ok, that's all I added :)

**Comment by vincentlv** [comment]
recently I try to build pyfftw in Mac OS 10.10, here is the warning:

************************
41 warnings generated.
cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.10-intel-2.7/Users/vincent/Downloads/pyFFTW-0.10.1/pyfftw/pyfftw.o -L/usr/local/lib -lfftw3 -lfftw3f -lfftw3l -lfftw3_threads -lfftw3f_threads -lfftw3l_threads -o build/lib.macosx-10.10-intel-2.7/pyfftw/pyfftw.so
ld: warning: ignoring file /usr/local/lib/libfftw3.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libfftw3.dylib
....
copying build/lib.macosx-10.10-intel-2.7/pyfftw/pyfftw.so -> pyfftw
...
***********************

As a result, I can import pyfftw, but its computed fft value is not correct. I assume that is because the build warning above, ld warning. I was thinking how I can delete the cc option -arch i386 above when building this package. I have already taken a day to install that packages....

**Comment by hgomersall** [comment]
@vincentlv I suggest that "/usr/local/lib/libfftw3.dylib, file was built for x86_64 which is not the architecture being linked (i386)" might be the useful error to follow up. Are you using 32-bit python on a 64-bit machine?

**Comment by vincentlv** [comment]
@hgomersall  64-bit machine, Mac OS 10.10.5

**Comment by hgomersall** [comment]
@vincentlv indeed, but are you running 32-bit python? See this: http://stackoverflow.com/questions/1405913/how-do-i-determine-if-my-python-shell-is-executing-in-32bit-or-64bit-mode-on-os

**Comment by vincentlv** [comment]
@hgomersall Based the url, it shows it's 64bit, in ipython.

**Comment by hgomersall** [comment]
In that case, I've no idea. I have virtually no experience with OSX - I suggest asking on stackoverflow (with a bit more information and attempts at self-help than you've given me).

**Comment by vincentlv** [comment]
@hgomersall  I manually re-gcc the file in command line, deleting the term "-arch i386". Then, no ld warning at all, and the pyfftw works well too.

The command is:
*****************
gcc -bundle -undefined dynamic_lookup -arch x86_64 -Wl,-F. build/temp.macosx-10.10-intel-2.7/Users/vincent/Downloads/pyFFTW-0.10.1/pyfftw/pyfftw.o -L/usr/local/lib -lfftw3 -lfftw3f -lfftw3l -lfftw3_threads -lfftw3f_threads -lfftw3l_threads -o build/lib.macosx-10.10-intel-2.7/pyfftw/pyfftw.so
*****************
Then cp the pyfftw.so to the folder pyfftw.

By the way, this packages is really great, much faster then numpy.fft!
Thanks

**Comment by hgomersall** [comment]
Good stuff. I've no idea why it was sticking -arch i386 into your argument list.

**Comment by hyliu1989** [comment]
The problem still persists and pip does not find my brew installed FFTW3. I ended up have to compile FFTW myself. And after that modifying pip install global path to link to the compiled FFTW library. The following is my recipe.



Install FFTW3 on a UNIX machine: 
(three sets for three different precisions)
(if openmp is not install, drop `--enable-openmp` from all three lines containing it)
`cd path/to/fftw3_setup_files/`

`./configure --prefix=/path/to/put/fftw3/ --enable-shared --with-pic --enable-sse2 --enable-threads --enable-openmp`
`make`
`make install`

`make distclean`
`./configure --prefix=/path/to/put/fftw3/ --enable-shared --with-pic --enable-sse2 --enable-threads --enable-openmp --enable-float`
`make`
`make install`

`make distclean`
`./configure --prefix=/path/to/put/fftw3/ --enable-shared --with-pic --enable-threads --enable-openmp --enable-long-double`
`make`
`make install`

Install pyfftw on UNIX Anaconda via pip install
`pip install --global-option=build_ext --global-option="-I/path/to/put/fftw3/include" --global-option="-L/path/to/put/fftw3/lib" pyfftw`

**Comment by hyliu1989** [comment]
Finally if there is a rpath problem, use the following
`install_name_tool -add_rpath "/path/to/anaconda/envs/python3/lib/" the_problematic_so_file.so`

Here, /path/to/anaconda/envs/python3/lib/ need to be changed to correct path that leads to the missing library if there is any missing.

**Comment by jakirkham** [comment]
Not sure if this is still an issue. Would recommend using the [conda-forge]( http://conda-forge.github.io/ ) package, which can be found [here]( https://anaconda.org/conda-forge/pyfftw ). That is a prebuilt binary designed to work on macOS 10.9+.

**Comment by cancan101** [comment]
somewhat related: https://github.com/pyFFTW/pyFFTW/issues/193

**Comment by alexandercbooth** [comment]
Following the mac instructions, including installing fftw with homebrew (I have anaconda as well), I ran into an import error at the `pip install pyfftw` step, 
```
ImportError...
 Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```
In case it helps anyone, I was able to fix this with the following,
```bash
DYLD_LIBRARY_PATH=/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/
pip install pyfftw
```

**Comment by grlee77** [comment]
@alexandercbooth :  You mention that you have `conda` as well.  In that case you can also try the conda-forge package mentioned above by `conda install -c conda-forge pyfftw`.  With the conda-forge approach it is not necessary to have installed FFTW itself previously.

**Comment by jakirkham** [comment]
Move to close this issue.

There are binaries in conda-forge that people can use. Work on wheels is being discussed/worked on in another issue.

**Comment by hgomersall** [comment]
Yeah, seems reasonable.
