### ISSUE TITLE
scipy interface patching.

### ISSUE THREAD

**Issue by anntzer** [pyFFTW/pyFFTW#68]
You may find https://github.com/scipy/scipy/pull/5295 helpful (TLDR: patching scipy's fftpack is essentially a simple `scipy.fftpack = pyfftw.interfaces.scipy_fftpack` now) and update the docs accordingly.

**Comment by hgomersall** [comment]
Ah useful! Thanks!

**Comment by hgomersall** [comment]
I'll update the documentation to reflect this.

**Comment by anntzer** [comment]
Slightly hijacking this thread:  Any chance we can have a Python3.5 Windows build on PyPI any time soon?  (The Gohlke build doesn't seem to work with Anaconda Python for me.)

**Comment by hgomersall** [comment]
Yes, the appveyor setup is building for 3.5. Once I've fixed an appveyor bug with 3.3 and 3.4, I'll make a release.

**Comment by anntzer** [comment]
Actually I figured out how to make the Gohlke build work for me, sorry for the bother.

**Comment by anntzer** [comment]
FYI, the monkey-patching docs at https://hgomersall.github.io/pyFFTW/sphinx/tutorial.html#quick-and-easy-the-pyfftw-interfaces-module still refer to the old method.

**Comment by hgomersall** [comment]
@anntzer I honestly thought I'd fixed some aspect of this. The presence of the issue and the lack of the change would suggest otherwise!

Anyway, this is fixed with #101, thanks!

**Comment by hgomersall** [comment]
Also, the link is also fixed.
