### ISSUE TITLE
FTBFS: TypeError: can't pickle Cython.Compiler.FlowControl.NameAssignment objects

### ISSUE THREAD

**Issue by ghisvail** [pyFFTW/pyFFTW#82]
Forwarding this bug caught by the Debian builders and reported [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810522). The build log is available in the bug report.

If this bug has been fixed, could you point me to the relevant commit to cherry-pick. Another solution is to have a new release.

Thanks,
Ghis

**Comment by hgomersall** [comment]
Yes, you're quite right. Things are definitely ripe for a release and I've set up the windows build system to make it pretty seamless. I'm waiting on an annoying appveyor test fail (it seems to be a timing issue with virtual machine contention), and then I'll make a release. Hopefully today.

I'm not sure if this will fix the problem, though python 3.5 is being targetted.

**Comment by hgomersall** [comment]
[This bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810645) may be pertinent. It doesn't stop the need for a release but suggests it's a python 3.5 bug.

**Comment by hgomersall** [comment]
Release made (now on 0.10.1 for frustrating reasons).

**Comment by ghisvail** [comment]
This is fixed with your latest release. Thanks @hgomersall for addressing this issue. Closing.
