### ISSUE TITLE
Avoid overwriting the version file distributed in the source release.

### ISSUE THREAD

**Issue by ghisvail** [pyFFTW/pyFFTW#87]
The source tarball of `0.10.1` comes with a release of a `version.py` file, which gets rewritten on subsequent calls to `setup.py`. This hurts the build reproducibility of the package. I overcame this by commenting line 377 of `setup.py` via a patch, but perhaps the design should be reconsidered for the next release.

Cheers,
Ghis

**Comment by ghisvail** [comment]
I should probably add that the Debian packaging is kept under a VCS, so although we are using the source release, `setup.py` still tries to update the git revision tag. The fix might just well be as simple as switching the test cases between line 328 and line 330.

**Comment by hgomersall** [comment]
It would be great if you could review the PR that attempts to address this (and the other issues referenced).

**Comment by hgomersall** [comment]
@ghisvail *bump*

**Comment by ghisvail** [comment]
Should be easy to test no? Just trying a build and checking the diff of `version.py`.

Regarding the docs, I'd have to test that on another release which includes them.

**Comment by hgomersall** [comment]
Yes, I can test it and it's fine, I just want a code review for sanity checking :)

**Comment by hgomersall** [comment]
As in, before I merge the PR.

**Comment by kohr-h** [comment]
Is this related to the current release of pyfftw having a `__version__` that is out of sync with the pip version (or conda-forge for that matter)? After doing this
```
pip install pyfftw==0.10.4
[...]
Successfully installed pyfftw-0.10.4
```
I get this:
```python
>>> import pyfftw
>>> pyfftw.__version__
'0.10.3.dev0+e827cb5'
```
But according to [this](https://github.com/pyFFTW/pyFFTW/blob/4dd6b6b2f330ec65adba0a2c14281a8e875b4d9a/setup.py#L392-L393) the version shouldn't have been rewritten (the linked `setup.py` is from the tagged commit for 0.10.4). So it seems that the release package has been generated from a different commit with `ISRELEASE = False`?

**Comment by grlee77** [comment]
closing this issue as resolved.  We are now using versioneer to automate handling of the version numbers (see #176).
