### ISSUE TITLE
PyFFTW returning all zero array after transform...

### ISSUE THREAD

**Issue by TrekkieByDay** [pyFFTW/pyFFTW#94]
I have a Python program that depends on a Fast Fourier Transform performed by PyFFTW.

All computers that I've tested my program on are Windows 7 or Windows 8 server. 

The program passes unit tests on all computers except one. 

In the case in which it fails, the problem is the result of the FFT: on this particular computer, PyFFTW returns an array of all ZEROS rather than the correctly populated array that all the other computers return. This is not just a difference in the machine precision, which is expected.

Without getting into the actual hardware specifics of the computer that fails (it is Windows 8 server, Intel processor, very similar to the other computers that pass)... what are the possible hardware / software differences that could result in such behavior? Watching the task manager, the computer appears to be doing the work that I would expect for the FFT... the expected RAM is used, the CPU is taxed as expected, the compute time is expected... but the final result is zeros. I am flummoxed. Thanks!

**Comment by hgomersall** [comment]
Is this the pyFFTW unittests, or your unittests? Can you show me a minimal failing example?

**Comment by TrekkieByDay** [comment]
I'm sorry I wasn't clear. My program's unit test. I'm working on creating a minimal example and figuring out just exactly where the zeros occur.

**Comment by TrekkieByDay** [comment]
Was just hoping that something would spring to mind quickly.

**Comment by hgomersall** [comment]
Well the planning process may well clobber the arrays which is in the documentation. The unittests are pretty comprehensive so there shouldn't be any bugs like you describe, and if there is I really want to know about it. Basically, without code, I can't help much.

**Comment by TrekkieByDay** [comment]
Working on it. I'll have a more distilled question later. Thanks.

**Comment by hgomersall** [comment]
Fine, closing in the mean time.

**Comment by TrekkieByDay** [comment]
Okay, so closing the issue was the right decision. :) Further investigation has uncovered that in fact it is NOT PyFFTW that is the culprit... it is Numerical Expressions. We are using Numexpr to do a very large array operation... and it turns out that, randomly, Numexpr will return a zeroed array rather than the correct result. No error is thrown... just a zero array of the appropriate size. So PyFFTW is off the hook!  Please forgive me for the error; initial testing indicated otherwise.

If you're interested....

...we used the following code to test this out. The error happens at random indices in the loop. We have only been able to produce this behavior using machines with Xenon processors. This is very disturbing. :(


    import numpy as np
    import numexpr as ne
    
    x = np.ones(1e6)
    y = np.ones(1e6)
    
    for ii in range(100):
        rr = ne.evaluate('x * y')
        test = np.all(rr == 0)
        if test:
            print('Gotcha! %d' % ii)
    print('Complete!')
    
    >>>
    Gotcha! 18
    Gotcha! 34
    Gotcha! 42
    Gotcha! 92

**Comment by hgomersall** [comment]
Interesting. I suggest filing a bug with the numexpr people.

**Comment by TrekkieByDay** [comment]
Yep! Just thought you'd be interested in that little tidbit. I know Numexpr is not your baby. Thanks for being so responsive.

**Comment by hgomersall** [comment]
Yes, i'm interested. An no probs :)
