### ISSUE TITLE
Incorrect links to docs

### ISSUE THREAD

**Issue by aganders3** [pyFFTW/pyFFTW#96]
The link to the documentation (GitHub Pages) is incorrect in your description and your readme.

Right now your links point to http://pyfftw.github.com/pyFFTW/, but they should point to http://pyfftw.github.io/pyFFTW/

Maybe this is something that changed on GitHub's side at some point.

**Comment by hgomersall** [comment]
Fixed, thank you for that. It was indeed a github server changed (I'd updated PyPI but not README.rst).
